# -*- coding: utf-8 -*-
"""10_Optimizer_ensemble_v14_gating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TG0OJ_I8fJEmshgPAWYrGLHukVHBNnfE

This script refactors the original grid-search approach for finding optimal
ensemble weights, incorporating Bayesian Optimization with Optuna and prediction
caching for dramatically improved efficiency and scientific robustness.

0. Set Up Environment
"""

!pip install albumentations torchinfo optuna h5py
!pip install git+https://github.com/qubvel/segmentation_models.pytorch

"""1. Imports"""

print("Importing libraries...")
# Install required packages if needed

from google.colab import drive
drive.mount('/content/drive')
import os
import atexit
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from datetime import datetime
import torch.nn.functional as F
import random
import shutil
import h5py # <--- Added
import cv2
import segmentation_models_pytorch as smp
import json
import warnings
import albumentations as A
from albumentations.pytorch import ToTensorV2
import optuna
from collections import defaultdict
from sklearn.metrics import average_precision_score
import gc

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

# =============================================================================
# Configuration
# =============================================================================
# Tip: Keep this section as the ONLY place you edit parameters.
# Everything below should read these variables without redefining them.
# =============================================================================

print("Configuring environment...")

# -----------------------------------------------------------------------------
# 1) Reproducibility
# -----------------------------------------------------------------------------
SEED = 24  # Master seed (used across subsampling, Optuna, holdout split, etc.)

# -----------------------------------------------------------------------------
# 2) Hardware / DataLoader performance
# -----------------------------------------------------------------------------
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

BATCH_SIZE = 32    # Lower this if you hit GPU OOM during ensemble inference
WORKERS = 4           # Increase carefully; too high can slow Colab/Drive I/O

# Cache directory for storing cached predictions (speeds up Optuna and eval)
PRED_CACHE_DIR = '/content/pred_cache'

# -----------------------------------------------------------------------------
# 3) Dataset locations
# -----------------------------------------------------------------------------
# Google Drive Folder containing VALIDATION.h5
HDF5_DRIVE_DIR = 'IA_MEDICA_SAMPLES/CAMELYON16'

# Local temporary directory on Colab (fast NVMe I/O)
LOCAL_DATA_DIR = '/content/dataset'

# -----------------------------------------------------------------------------
# 5) Model selection (which checkpoints enter the ensemble)
# -----------------------------------------------------------------------------
N_TOP_MODELS = 8  # Number of models included in the ensemble

# Folder containing *_meta.json files for candidate models
METADATA_DIR = "METADATA_CHECKPOINTS/CAMELYON16"

# How to rank models to pick top-N from metadata
SORT_METRIC = "best_val_auprc_pixel_score"

# Optional: override dropout in decoder at inference (usually keep 0 for deterministic eval)
DECODER_DROPOUT = 0

# -----------------------------------------------------------------------------
# 6) Output / Environment bookkeeping
# -----------------------------------------------------------------------------
OUTPUT_DIR = "RESULTS_REPORT_ENSEMBLE/CAMELYON16"  # where reports + json are saved

# These look like personal bookkeeping paths (can be removed if not used elsewhere)
WHERE_WAS_CREATED = '/content/drive/MyDrive/Personal_Drive_Bruno/'
CURRENT_ENV = '/content/drive/MyDrive/'

# -----------------------------------------------------------------------------
# 9) Optuna Stage 1: ensemble weights optimization
# -----------------------------------------------------------------------------

# Chunk sizes used to keep RAM stable during ensemble aggregation + threshold scans
OPTUNA_ENSEMBLE_CHUNK = 4096  # chunk over N pixels when building ensemble (reduce if RAM spikes)
THRESH_SCAN_CHUNK = 4096      # chunk size inside threshold scanning loops (reduce if RAM spikes)

# Number of candidate thresholds tested during Optuna trials and final threshold selection
THRESH_NUM_STEPS_TRIALS = 100
# -----------------------------------------------------------------------------
# 11) Validation holdout split (for honest evaluation of recipe)
# -----------------------------------------------------------------------------
# Split the validation into: (a) opt_pool for choosing weights/threshold
# and (b) holdout to estimate generalization before touching TEST.
VAL_HOLDOUT_FRAC = 0.20
VAL_HOLDOUT_SEED = SEED + 123

# =============================================================================
# 5) Model Grouping & Optimization Config
# =============================================================================
# Architecture grouping (Configurable)
SEMANTIC_ARCHS = ["SWIN", "DPT", "SEGFORMER", "UPERNET"] # Add others as needed
SPATIAL_ARCHS  = ["DEEPLABV3PLUS", "UNET++", "FPN", "MANET"]
#SPATIAL_ARCHS  = ["DEEPLABV3PLUS", "UNET++", "MANET", "INCEPTIONRESNETV2"]

# ROI Generation & Guardrails
ROI_CONTEXT_SCALE = 4      # Downsample factor for "coarse" view
ROI_MAX_MEDIAN    = 0.60   # Max allowed median area fraction
ROI_EMPTY_MAX     = 0.50   # Max allowed fraction of empty ROIs
ROI_MIN_POS_RECALL= 0.80   # Min required recall of GT positives by ROI - Better use 0.95

# Spatial Optimization
SPILL_PENALTY_LAMBDA = 0.10
SPATIAL_PATIENT_POLICY = "positive_only" # or "all"

# Optimization Settings
N_OPTUNA_TRIALS_SEM = 50
N_OPTUNA_TRIALS_SPA = 50

def change_path(path, possible_paths=None):
    if possible_paths is None:
        possible_paths = [
            '/content/drive/MyDrive/Personal_Drive_Bruno/',
            '/content/drive/MyDrive/'
        ]

    for p in possible_paths:
        # Create a new variable here so 'path' stays original
        full_path = os.path.join(p, path)

        if os.path.exists(full_path):
            return full_path

    # Use the original path in the error message for clarity
    raise ValueError(f"The path {path} does not match any known environments.")

# --- Seeding & Reproducibility ---
def seed_everything(seed=42):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # CRITICAL FOR REVIEWER 1:
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False  # Must be False for reproducibility
    try:
      torch.use_deterministic_algorithms(True, warn_only=True)
    except TypeError:
      torch.use_deterministic_algorithms(True)

    # Required for some CUDA operations (Resize, etc.) to be deterministic
    os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"

seed_everything(SEED)

print(f"Reproducibility configured. SEED={SEED}")

def setup_inference_precision(architecture: str):
    """
    Sets global precision flags and returns the autocast dtype for inference.
    (Simplified version of training setup: No GradScaler needed).
    """

    architecture = str(architecture).upper().strip()

    # --- TIER 1: STRICT FP32 (DPT) ---
    if architecture == "DPT":
        try:
            torch.set_float32_matmul_precision('highest') # IEEE FP32
        except Exception:
            pass
        return torch.float32

    # --- TIER 2: MEDIUM PRECISION (Transformers) ---
    if architecture in ["SWIN", "SEGFORMER"]:
        try:
            torch.set_float32_matmul_precision('medium') # BF16/TF32 MatMul
        except Exception:
            pass
    else:
        # --- TIER 3: HIGH PRECISION (CNNs/Standard) ---
        try:
            torch.set_float32_matmul_precision('high') # TF32 MatMul
        except Exception:
            pass

    # --- AMP Dtype Selection ---
    # Use BF16 if available (more stable than FP16), otherwise FP16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
        return torch.bfloat16
    else:
        return torch.float16

# --- Helper Functions ---
def get_formatted_datetime_string():
  now = datetime.now()
  return now.strftime("%d_%m_%Y_%H_%M_%S")

def get_model(architecture, encoder, validation=False):

    # Validation optimization: No need to download ImageNet weights if loading a checkpoint
    encoder_weights = None if validation else "imagenet"

    # Common args for all architectures
    common_args = dict(
        encoder_name=encoder,
        encoder_weights=encoder_weights,
        in_channels=3,
        classes=2,        # Correct for your 2-channel One-Hot masks
        activation=None,  # Correct for BCEDiceHybridLoss (expects logits)
    )

    arch = architecture.upper()

    if arch == "SWIN":
        # Swin works best as a backbone for U-Net or UPerNet
        model = smp.Unet(**common_args, decoder_attention_type=None)

    elif arch == "DEEPLABV3PLUS":
        model = smp.DeepLabV3Plus(**common_args, decoder_attention_type=None)

    elif arch == "DPT":
        # DPT specific: Ignore the depth readout, strictly segmentation
        model = smp.DPT(**common_args, decoder_readout='ignore')

    elif arch == "UNET++":
        model = smp.UnetPlusPlus(**common_args, decoder_attention_type=None)

    elif arch == "FPN":
        model = smp.FPN(**common_args, decoder_attention_type=None)

    elif arch == "SEGFORMER":
        model = smp.Segformer(**common_args, decoder_attention_type=None)

    elif arch == "MANET":
        model = smp.MAnet(**common_args, decoder_attention_type=None)

    elif arch == "UPERNET":
        model = smp.UPerNet(**common_args, decoder_attention_type=None)

    elif arch == "INCEPTIONRESNETV2":
         model = smp.Unet(**common_args, decoder_attention_type=None)

    else:
        raise ValueError(f"Unknown architecture: {architecture}")

    return model

class SubsetWithPos(torch.utils.data.Dataset):
    def __init__(self, ds, indices):
        self.ds = ds
        self.indices = list(indices)
    def __len__(self):
        return len(self.indices)
    def __getitem__(self, pos):
        sample = self.ds[self.indices[pos]]
        if sample[0] is None:  # preserve your None behavior
            return (None,) * (len(sample) + 1)
        return (*sample, pos)  # append pos

def clear_gpu():
    print("Clearing GPU cache...")
    if torch.cuda.is_available():
        try:
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()
        except Exception as e:
            # Optional: only print if something really went wrong
            print(f"[clear_gpu] Warning: {e}")
    print("GPU cache cleared.")

def load_and_select_models(metadata_dir, n_top_models, sort_metric):
    # --- Validate sort_metric ---
    valid_sort_metrics = ["best_validation_DICE","best_val_auprc_pixel_score"]
    if sort_metric not in valid_sort_metrics:
        raise ValueError(f"Invalid sort_metric: '{sort_metric}'. Must be one of {valid_sort_metrics}")

    metadata_files = [os.path.join(metadata_dir, f) for f in os.listdir(metadata_dir) if f.endswith("_meta.json")]
    if not metadata_files:
        raise FileNotFoundError(f"No metadata files found in {metadata_dir}")

    all_metadata = []
    print(f"Loading metadata from {metadata_dir}...")
    for f_path in tqdm(metadata_files, desc="Loading Metadata"):
        try:
            with open(f_path, 'r') as f:
                meta = json.load(f)
                meta['metadata_filename'] = os.path.basename(f_path) # Add filename

                # --- Validate the sort metric value BEFORE adding ---
                metric_value = meta.get(sort_metric)
                if metric_value is not None and isinstance(metric_value, (int, float)) and not np.isnan(metric_value): # Check for NaN too
                    all_metadata.append(meta)
                else:
                    print(f"\nWarning: Skipping {os.path.basename(f_path)} - missing, non-numeric, or NaN sort metric '{sort_metric}' (value: {metric_value}).")
        except Exception as e:
            print(f"\nError loading metadata from {f_path}: {e}")

    if not all_metadata:
         raise ValueError("No valid metadata loaded after filtering for sort metric.")

    # --- Determine Sort Order based on the validated sort_metric ---
    if sort_metric == "best_validation_DICE":
        sort_descending = True # Maximize Optimized Dice
        # Default value for sorting if key is missing (shouldn't happen after filter)
        default_sort_value = -np.inf
    elif sort_metric == "best_val_auprc_pixel_score":
        sort_descending = True # Maximize Validation Dice
        default_sort_value = -np.inf
    # No else needed due to initial validation

    # --- Sort the list ---
    try:
        all_metadata.sort(
            key=lambda x: x.get(sort_metric, default_sort_value), # Use validated metric
            reverse=sort_descending
        )
        print(f"\nSorted {len(all_metadata)} models by '{sort_metric}' ({'Descending' if sort_descending else 'Ascending'}).")
    except Exception as e:
        print(f"Error during sorting: {e}")
        raise

    # --- Select Top N ---
    print(f"\n--- Selecting Top {n_top_models} Models based on {sort_metric} ---")
    top_models_meta = all_metadata[:n_top_models]
    if len(top_models_meta) < n_top_models:
        print(f"Warning: Only found {len(top_models_meta)} valid models after sorting, using all of them.")
    if not top_models_meta:
         raise ValueError("No models available after sorting and selection.")

    # Print selected models
    for i, meta in enumerate(top_models_meta):
        metric_val_display = meta.get(sort_metric, 'N/A')
        try: # Format as float if possible
            metric_display_str = f"{metric_val_display:.4f}"
        except:
            metric_display_str = str(metric_val_display) # Fallback to string

        print(f" {i+1}. Arch: {meta.get('architecture', 'N/A')}, Enc: {meta.get('encoder', 'N/A')}, "
              f"{sort_metric}: {metric_display_str}, " # Use formatted string
              f"Checkpoint: {os.path.basename(meta.get('checkpoint_path', 'N/A'))}")
    print("-" * 60) # Adjusted separator width

    return top_models_meta

def get_stream_type(arch_name):
    arch_name = arch_name.upper()
    if any(s in arch_name for s in SEMANTIC_ARCHS): return 'semantic'
    if any(s in arch_name for s in SPATIAL_ARCHS): return 'spatial'
    return 'spatial' # Default fallback

def generate_roi_batch(probs_tensor, context_scale, threshold):
    """
    Generates binary ROI masks using low-pass approach:
    Downsample -> Threshold -> Upsample (Nearest)
    Input: probs_tensor [B, H, W] (float)
    Output: roi_mask [B, H, W] (bool/uint8)
    """
    B, H, W = probs_tensor.shape
    # 1. Downsample (Low-pass)
    # Unsqueeze for interpolate [B, 1, H, W]
    small = F.interpolate(probs_tensor.unsqueeze(1), scale_factor=1.0/context_scale, mode='bilinear', align_corners=False)

    # 2. Threshold (Operating Point)
    mask_small = (small > threshold).float()

    # 3. Upsample (Nearest to keep binary edges)
    mask_large = F.interpolate(mask_small, size=(H, W), mode='nearest').squeeze(1)

    return mask_large # [B, H, W] 0.0 or 1.0

def compute_patient_auprc_in_roi(y_true, y_pred, roi_mask):
    """
    Compute AUPRC only for pixels INSIDE the ROI.
    y_true, y_pred, roi_mask: flattened 1D arrays for a single patient.
    """
    # Filter by ROI
    valid_indices = (roi_mask > 0)

    # Guard: Empty ROI
    if not np.any(valid_indices):
        return 0.0

    y_true_roi = y_true[valid_indices]
    y_pred_roi = y_pred[valid_indices]

    # Guard: No positive pixels in ROI (Target is all 0) -> AUPRC undefined/0
    if np.sum(y_true_roi) == 0:
        return 0.0

    try:
        return average_precision_score(y_true_roi, y_pred_roi)
    except:
        return 0.0

@torch.inference_mode()
def predict_with_tta_batched(model, images, amp):
    """
    TTA = {orig, hflip, vflip} executed SEQUENTIALLY to save memory.

    Previous version: [3*B, C, H, W] -> Peak Memory: High
    This version:     [B, C, H, W] x 3 -> Peak Memory: Low (1/3rd)
    """
    # 1. Forward Pass (Original)
    with torch.amp.autocast('cuda', enabled=True, dtype=amp):
        out = model(images)
        if isinstance(out, (tuple, list)): out = out[0]

        # Convert to probabilities
        if out.shape[1] == 1:
            probs = torch.sigmoid(out).squeeze(1)
        else:
            probs = torch.softmax(out, dim=1)[:, 1, :, :]

    # 2. Horizontal Flip (Input Flip -> Forward -> Output Flip)
    images_h = torch.flip(images, dims=[3])
    with torch.amp.autocast('cuda', enabled=True, dtype=amp):
        out_h = model(images_h)
        if isinstance(out_h, (tuple, list)): out_h = out_h[0]

        if out_h.shape[1] == 1:
            p_h = torch.sigmoid(out_h).squeeze(1)
        else:
            p_h = torch.softmax(out_h, dim=1)[:, 1, :, :]

    # Accumulate in-place (Un-flip Width axis 2)
    probs.add_(torch.flip(p_h, dims=[2]))
    # Free memory immediately
    del images_h, out_h, p_h

    # 3. Vertical Flip
    images_v = torch.flip(images, dims=[2])
    with torch.amp.autocast('cuda', enabled=True, dtype=amp):
        out_v = model(images_v)
        if isinstance(out_v, (tuple, list)): out_v = out_v[0]

        if out_v.shape[1] == 1:
            p_v = torch.sigmoid(out_v).squeeze(1)
        else:
            p_v = torch.softmax(out_v, dim=1)[:, 1, :, :]

    # Accumulate in-place (Un-flip Height axis 1)
    probs.add_(torch.flip(p_v, dims=[1]))
    # Free memory
    del images_v, out_v, p_v

    # Average
    probs.div_(3.0)
    return probs

def cache_predictions_sequential(models_list, dataloader, device, cache_dir):
    print(f"\n--- Caching Predictions (Sequential, Optimized Uint16) to {cache_dir} ---")
    if os.path.exists(cache_dir): shutil.rmtree(cache_dir)
    os.makedirs(cache_dir, exist_ok=True)

    # 1. Initialize sizes
    print("Initializing cache size...")
    N_total = 0
    H, W = 0, 0
    for b in dataloader:
        if b is None: continue
        img = b[0]
        if img is not None:
            N_total += img.shape[0]
            if H == 0: H, W = img.shape[2], img.shape[3]
            # Break after first valid batch to save time
            break

    # Recalculate N_total correctly
    N_total = len(dataloader.dataset)
    print(f"Total samples: {N_total}, Shape: {H}x{W}")

    # Memmap for GTs (uint8)
    trues_path = os.path.join(cache_dir, "trues.dat")
    trues_mm = np.memmap(trues_path, dtype='uint8', mode='w+', shape=(N_total, H, W))

    pred_paths = []
    pids = []

    # 2. Sequential Model Inference
    first_pass = True

    for m_idx, model in enumerate(models_list):
        arch = getattr(model, 'arch_name', 'UNK')
        print(f"Processing Model {m_idx+1}/{len(models_list)}: {arch}")

        model.to(device).eval()
        amp = setup_inference_precision(arch)

        # OPTIMIZATION: Use uint16 to save 50% disk I/O and space
        p_path = os.path.join(cache_dir, f"pred_{m_idx}.dat")
        pred_mm = np.memmap(p_path, dtype='uint16', mode='w+', shape=(N_total, H, W))

        w_pos = 0
        for batch in tqdm(dataloader, desc=f"Infer {arch}"):
            if batch is None: continue

            # Handle tuple size variation
            if len(batch) == 3: imgs, masks, batch_pids = batch
            elif len(batch) == 4: imgs, _, masks, batch_pids = batch
            else: imgs, _, masks, batch_pids, _ = batch

            bs = imgs.shape[0]

            # Save GTs/PIDs only on first pass
            if first_pass:
                trues_mm[w_pos:w_pos+bs] = masks[:, 1, :, :].cpu().numpy().astype('uint8')
                pids.extend(batch_pids)

            # Inference
            imgs = imgs.to(device)
            imgs = gpu_normalizer(imgs) # <--- INSERTED HERE
            p = predict_with_tta_batched(model, imgs, amp)
            p = p.detach().float().cpu().numpy()


            # --- SAFETY GUARD FOR DPT/MANET ---
            # 1. Handle potential NaNs from the model itself (replace with 0.0)
            # 2. Handle rare float errors slightly < 0 or > 1
            # 3. Ensure strictly [0, 1] before scaling
            p = np.nan_to_num(p, nan=0.0, posinf=1.0, neginf=0.0)
            p = np.clip(p, 0.0, 1.0)

            # OPTIMIZATION: Quantize to uint16 (0-65535)
            # This preserves 1.5e-5 precision, sufficient for scientific segmentation
            p_quantized = (p * 65535).astype(np.uint16)

            pred_mm[w_pos:w_pos+bs] = p_quantized
            w_pos += bs


        pred_mm.flush()
        model.cpu()
        clear_gpu()

        pred_paths.append(p_path)
        if first_pass:
            trues_mm.flush()
            first_pass = False

    if w_pos != N_total:
        raise RuntimeError(f"Cached {w_pos} samples but expected {N_total}. Dataset produced None/filtered items.")

    with open(os.path.join(cache_dir, "pids.json"), 'w') as f: json.dump(pids, f)

    return pred_paths, trues_path, os.path.join(cache_dir, "pids.json"), N_total, H, W, trues_mm

# --- NEW: Post-Processing Logic ---
def postprocess_binary_mask_np(pred_mask_uint8, min_area, open_ksize):
    """
    Applies morphological opening and area filtering to a binary mask (H, W).
    Input: pred_mask_uint8 (0 or 1), numpy array.
    """
    # 1. Morphological Opening
    if open_ksize > 0:
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (open_ksize, open_ksize))
        pred_mask_uint8 = cv2.morphologyEx(pred_mask_uint8, cv2.MORPH_OPEN, kernel)

    # 2. Area Filtering
    if min_area > 0:
        # cv2.connectedComponentsWithStats takes uint8 image
        num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(pred_mask_uint8, connectivity=8)

        # stats: [x, y, width, height, area]
        # Label 0 is background
        for i in range(1, num_labels):
            area = stats[i, cv2.CC_STAT_AREA]
            if area < min_area:
                pred_mask_uint8[labels == i] = 0

    return pred_mask_uint8

def compute_global_metrics_from_counts(tp: int, fp: int, fn: int, tn: int, smooth: float = 1e-6):
    """
    Compute micro Dice, IoU and MCC from global TP/FP/FN/TN counts.

    Returns:
        dice_micro (float), iou (float), mcc (float)
    """
    # Micro Dice over all pixels
    denom_dice = 2 * tp + fp + fn
    if denom_dice > 0:
        dice_micro = float((2.0 * tp + smooth) / (denom_dice + smooth))
    else:
        dice_micro = 0.0

    # IoU (Jaccard)
    denom_iou = tp + fp + fn
    if denom_iou > 0:
        iou = float((tp + smooth) / (denom_iou + smooth))
    else:
        iou = 0.0

    # Matthews Correlation Coefficient
    tp_fp = tp + fp
    tp_fn = tp + fn
    tn_fp = tn + fp
    tn_fn = tn + fn

    denom_mcc = (tp_fp * tp_fn * tn_fp * tn_fn) ** 0.5
    if denom_mcc > 0:
        mcc = float((tp * tn - fp * fn) / (denom_mcc + 1e-12))
    else:
        mcc = 0.0

    return dice_micro, iou, mcc

def change_paths(top_models_metadata):
  for meta in top_models_metadata:
      if not os.path.exists(meta['checkpoint_path']):
          new_path = str(meta['checkpoint_path']).replace(WHERE_WAS_CREATED, CURRENT_ENV)
          if os.path.exists(new_path):
              meta['checkpoint_path'] = new_path
              print(f"Updated path for {meta['checkpoint_path']}")
          else:
              print(f"Path not found: {new_path}")
  return top_models_metadata

def setup_local_hdf5(drive_dir, local_dir):
    """Copies HDF5 files from Drive to local VM for speed."""
    print(f"\n{'='*25} Setting up HDF5 Data {'='*25}")
    if os.path.exists(local_dir): shutil.rmtree(local_dir)
    os.makedirs(local_dir, exist_ok=True)

    # We strictly need VALIDATION.h5 for the optimizer
    filename = "VALIDATION.h5"
    resolved_drive_dir = change_path(drive_dir) # Use your existing path resolver

    src = os.path.join(resolved_drive_dir, filename)
    dst = os.path.join(local_dir, filename)

    if not os.path.exists(src):
        raise FileNotFoundError(f"Missing {src}")

    print(f"Copying {filename}...")
    shutil.copy2(src, dst)
    return dst

# --- AUGMENTATION PIPELINE (Strictly Updated for Albumentations 1.4+ & nnU-Net) ---
def get_transforms(mode="train", img_size=224):
    if mode == "train":
        return A.Compose([
            # 2. GEOMETRIC INVARIANCE
            A.HorizontalFlip(p=0.5),
            A.VerticalFlip(p=0.5),

            # Affine replacement for ShiftScaleRotate (Strict 1.4 API)
            A.Affine(
                scale=(0.9, 1.1),
                translate_percent=(-0.0625, 0.0625),
                rotate=(-45, 45),
                fill=0,
                fill_mask=0,
                border_mode=cv2.BORDER_CONSTANT,
                p=0.5
            ),

            # 3. COLOR & INTENSITY ROBUSTNESS
            A.OneOf([
                A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=1.0),
                A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=1.0),
                A.RGBShift(r_shift_limit=20, g_shift_limit=20, b_shift_limit=20, p=1.0),
                # Gamma Augmentation (nnU-Net Page 11, Item 7)
                A.RandomGamma(gamma_limit=(80, 120), p=1.0),
            ], p=0.8),

            # 4. ARTIFACT & QUALITY SIMULATION
            A.OneOf([
                A.GaussianBlur(blur_limit=(3, 5), p=1.0),
                # GaussNoise (Strict 1.4 API: std_range as fraction of 255)
                A.GaussNoise(std_range=(0.01, 0.05), mean_range=(0.0, 0.0), p=1.0),

                # REPLACEMENT: Downscale (Strict 1.4 API + nnU-Net Logic)
                # nnU-Net: downsample factor U(1, 2) -> scale 0.5 to 1.0
                # nnU-Net: Down=Nearest, Up=Cubic
                A.Downscale(
                    scale_range=(0.5, 0.9),
                    interpolation_pair={
                        "downscale": cv2.INTER_NEAREST,
                        "upscale": cv2.INTER_CUBIC
                    },
                    p=1.0
                ),
            ], p=0.2),

            # 5. REGULARIZATION (CoarseDropout / Cutout)
            # Strict 1.4 API: num_holes_range, fill
            A.CoarseDropout(
                num_holes_range=(1, 8),
                hole_height_range=(1, int(img_size/10)),
                hole_width_range=(1, int(img_size/10)),
                fill=0,
                fill_mask=0,
                p=0.2
            ),

            ToTensorV2(),
        ])

    else: # Validation / Test (Deterministic)
        return A.Compose([
            ToTensorV2(),
        ])

class ProstateCancerDatasetHDF5(Dataset):
    def __init__(
        self,
        hdf5_path,
        mode="validation",
        return_context=False, # Required for Stage 2 Gating
        context_scale=1       # Required for LowPass simulation
    ):
        self.hdf5_path = hdf5_path
        self.mode = mode
        self.return_context = return_context
        self.context_scale = int(context_scale)

        self.transform = get_transforms(mode=mode, img_size=224)

        # --- METADATA LOADING ---
        with h5py.File(self.hdf5_path, 'r') as f:
            self.full_pids = f["patient_ids"][:]
            self.total_len = len(self.full_pids)

        self.h5_file = None
        self.images_dset = None
        self.masks_dset = None
        self._opened_pid = None
        self._atexit_registered = False

    def _open_file(self):
        """Open the HDF5 file lazily (per-process safe).

        DataLoader with num_workers>0 forks/spawns worker processes. Each worker must
        hold its own independent HDF5 file handle. We therefore:
          - open on first access inside the current process
          - if the dataset object crosses a process boundary, close/reopen
          - register an atexit hook (once per process) to close cleanly
        """
        pid = os.getpid()

        # If we were opened in a different process (e.g., fork), close and reopen here.
        if self.h5_file is not None and self._opened_pid is not None and self._opened_pid != pid:
            self.close()

        if self.h5_file is None:
            # 50MB raw data chunk cache is sufficient for sequential-ish reading
            self.h5_file = h5py.File(
                self.hdf5_path,
                "r",
                libver="latest",
                rdcc_nbytes=50 * 1024 * 1024,
            )
            self.images_dset = self.h5_file["images"]
            self.masks_dset = self.h5_file["masks"]
            self._opened_pid = pid

            if not self._atexit_registered:
                # Ensure clean close when worker exits (best-effort).
                atexit.register(self.close)
                self._atexit_registered = True

    def __len__(self):
        return self.total_len

    def __getitem__(self, idx):
        if self.h5_file is None: self._open_file()

        # 1. Load Raw Data
        image = self.images_dset[idx] # uint8 [224,224,3]
        mask  = self.masks_dset[idx]  # uint8 [224,224]
        patient_id = str(self.full_pids[idx]) # Ensure string ID

        # 2. Prepare Mask (2-channel float for consistency)
        two_channel_mask = np.zeros((mask.shape[0], mask.shape[1], 2), dtype=np.float32)
        two_channel_mask[mask == 0, 0] = 1.0
        two_channel_mask[mask != 0, 1] = 1.0

        try:
            # 3. Augmentations
            augmented = self.transform(image=image, mask=two_channel_mask)
            final_image = augmented['image'] # Tensor [3, 224, 224]
            final_mask = augmented['mask']   # Tensor [224, 224, 2] usually

            # Fix Permutation: Albumentations returns (H,W,C), PyTorch needs (C,H,W)
            if final_mask.shape[0] != 2:
                final_mask = final_mask.permute(2, 0, 1)
            if final_mask.ndim != 3 or final_mask.shape[0] != 2:
              raise ValueError(
                  f"[HDF5Dataset] Unexpected mask shape after transforms: {tuple(final_mask.shape)} "
                  f"(expected (2,H,W)). Check Albumentations pipeline / ToTensorV2 behavior."
              )

            # 4. Context Gating (LowPass Simulation)
            if self.return_context:
                _, h, w = final_image.shape
                scale = max(1, self.context_scale)
                small_h, small_w = h // scale, w // scale

                # Downsample -> Upsample (Simulate Zoom Out)
                img_unsqueezed = final_image.unsqueeze(0)
                ctx_small = F.interpolate(img_unsqueezed, size=(small_h, small_w), mode='bilinear', align_corners=False)
                ctx_full = F.interpolate(ctx_small, size=(h, w), mode='bilinear', align_corners=False)

                final_context = ctx_full.squeeze(0)

                # Return 4 items: Image, Context, Mask, PID
                return final_image, final_context, final_mask, patient_id

            return final_image, final_mask, patient_id

        except Exception as e:
            print(f"Error on index {idx}: {e}")
            if self.return_context: return None, None, None, None
            return None, None, None

    # Required for stratifying holdout sets
    def get_patient_ids(self):
        return [str(p) for p in self.full_pids]

    def close(self):
        """Close any open HDF5 handle (safe to call multiple times)."""
        try:
            if getattr(self, "h5_file", None) is not None:
                try:
                    self.h5_file.close()
                except Exception:
                    pass
        finally:
            self.h5_file = None
            self.images_dset = None
            self.masks_dset = None
            self._opened_pid = None

    def __del__(self):
        # Best-effort cleanup (do not raise in GC).
        try:
            self.close()
        except Exception:
            pass

    def __getstate__(self):
        """Make dataset picklable by dropping live HDF5 handles."""
        state = self.__dict__.copy()
        # Never pickle open file handles / datasets.
        state["h5_file"] = None
        state["images_dset"] = None
        state["masks_dset"] = None
        state["_opened_pid"] = None
        state["_atexit_registered"] = False
        return state

    def __setstate__(self, state):
        self.__dict__.update(state)
        # Ensure handles are closed until first access in this process.
        self.h5_file = None
        self.images_dset = None
        self.masks_dset = None
        self._opened_pid = None
        self._atexit_registered = False

class GPUNormalizer(torch.nn.Module):
    def __init__(self, mean, std, device):
        super().__init__()
        # Register as buffers so they move to device automatically with the model
        self.register_buffer("mean", torch.tensor(mean, device=device).view(1, 3, 1, 1))
        self.register_buffer("std", torch.tensor(std, device=device).view(1, 3, 1, 1))

    @torch.no_grad()
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Input x: [B, 3, H, W]
        """
        # CASE 1: Input is Byte/Uint8 (0-255).
        # This is what comes from ToTensorV2() with uint8 source.
        if x.dtype == torch.uint8:
            x = x.float() / 255.0

        # CASE 2: Input is Float, but large magnitude (0-255).
        # This happens if an augmentation inadvertently cast to float but didn't normalize.
        # We use a safe threshold. ImageNet data is never > 10.0 after normalization.
        elif x.max() > 2.0:
             x = x / 255.0

        # CASE 3: Input is already float [0, 1].
        # We do nothing.

        # Finally, normalize with Mean/Std
        return (x - self.mean) / self.std

# --- SHARED: Updated Collate Function ---
def collate_fn(batch):
    # Filter None
    batch = list(filter(lambda x: x is not None and x[0] is not None, batch))
    if not batch: return None

    # Detect tuple size from first valid item
    sample_len = len(batch[0])

    if sample_len == 3:
        # Standard: (img, mask, pid)
        images = torch.utils.data.dataloader.default_collate([b[0] for b in batch])
        masks = torch.utils.data.dataloader.default_collate([b[1] for b in batch])
        pids = [b[2] for b in batch]
        return images, masks, pids

    elif sample_len == 4:
        # Context: (img, img_ctx, mask, pid)
        images = torch.utils.data.dataloader.default_collate([b[0] for b in batch])
        images_ctx = torch.utils.data.dataloader.default_collate([b[1] for b in batch])
        masks = torch.utils.data.dataloader.default_collate([b[2] for b in batch])
        pids = [b[3] for b in batch]
        return images, images_ctx, masks, pids

    elif sample_len == 5:
        images = torch.utils.data.dataloader.default_collate([b[0] for b in batch])
        images_ctx = torch.utils.data.dataloader.default_collate([b[1] for b in batch])
        masks = torch.utils.data.dataloader.default_collate([b[2] for b in batch])
        pids = [b[3] for b in batch]
        pos = torch.as_tensor([b[4] for b in batch], dtype=torch.long)
        return images, images_ctx, masks, pids, pos

    else:
        raise ValueError(f"Unexpected batch item length: {sample_len}")

def load_checkpoint_strict_without_aux(model, chkpt_path, device):
    # 1) Load checkpoint safely on CPU
    chkpt = torch.load(chkpt_path, map_location="cpu")

    # 2) Extract model state dict
    state_dict = chkpt.get("model_state_dict", chkpt)

    # 3) Drop auxiliary / classification head keys if present
    state_dict = {
        k: v for k, v in state_dict.items()
        if not k.startswith("classification_head.")
    }

    # 4) Load STRICTLY while model is still on CPU
    missing, unexpected = model.load_state_dict(state_dict, strict=True)

    if unexpected:
        print(f"[WARN] Unexpected keys: {unexpected[:5]}{'...' if len(unexpected) > 5 else ''}")
    if missing:
        print(f"[WARN] Missing keys: {missing[:5]}{'...' if len(missing) > 5 else ''}")

    # 5) Move model to device (single allocation)
    model.to(device)

    # 6) Re-compile ONLY if original model was compiled
    if chkpt.get("is_compiled", False):
        print("[INFO] Re-compiling model (checkpoint was compiled)")
        try:
            model = torch.compile(model)
        except Exception as e:
            print(f"[WARN] torch.compile failed: {e}")

    return model

def compute_metrics_histogram(weights, trues_mm, indices, H, W, chunk_size, tpr_target, sec_metric, pred_mms):
    """
    Computes global metrics for ALL thresholds simultaneously using histograms.
    Complexity: O(N) over pixels (single pass) + O(B) over bins, instead of O(N * T).
    Optimized aggregation via np.bincount (faster than np.add.at).
    """

    # 1) Setup Histograms
    # 4096 bins gives resolution of ~0.00024
    N_BINS = 4096
    hist_pos = np.zeros(N_BINS + 1, dtype=np.int64)
    hist_neg = np.zeros(N_BINS + 1, dtype=np.int64)

    weights = np.asarray(weights, dtype=np.float32)

    # Filter active weights to reduce compute
    active_m_indices = [i for i, w in enumerate(weights) if w > 1e-5]
    active_weights = weights[active_m_indices]

    # Precompute effective weights for uint16 decoding:
    # pred_uint16 in [0,65535] -> prob in [0,1] via * (1/65535)
    # fused into weight multiplication for speed
    active_w_eff = active_weights * (1.0 / 65535.0)

    # 2) Stream Data and Build Histograms
    # Ensure indices are numpy for slicing speed (optional but usually helpful)
    indices = np.asarray(indices)

    for i in range(0, len(indices), chunk_size):
        chunk_idx = indices[i:i + chunk_size]

        # Load GT (boolean mask)
        gt_chunk = (trues_mm[chunk_idx] > 0)

        # Weighted ensemble probability for this chunk
        ens_chunk = np.zeros(gt_chunk.shape, dtype=np.float32)

        # Accumulate only active models
        for local_i, global_m_i in enumerate(active_m_indices):
            raw_u16 = pred_mms[global_m_i][chunk_idx]  # uint16 memmap slice
            ens_chunk += raw_u16.astype(np.float32) * active_w_eff[local_i]

        # Clip to [0,1] (safety)
        np.clip(ens_chunk, 0.0, 1.0, out=ens_chunk)

        # Quantize to bins: p in [0,1] -> bin in [0, N_BINS]
        # Important: clip to N_BINS to avoid rare overflow due to float rounding at 1.0
        bin_indices = (ens_chunk * N_BINS).astype(np.int32)
        np.clip(bin_indices, 0, N_BINS, out=bin_indices)

        # Split into pos/neg bins and aggregate via bincount
        pos_bins = bin_indices[gt_chunk].ravel()
        if pos_bins.size:
            hist_pos += np.bincount(pos_bins, minlength=N_BINS + 1)

        neg_bins = bin_indices[~gt_chunk].ravel()
        if neg_bins.size:
            hist_neg += np.bincount(neg_bins, minlength=N_BINS + 1)

    # 3) Compute Metrics via Cumulative Sums (suffix sums over bins)
    # We want counts for p >= thr, which corresponds to bin >= b.
    # Reverse + cumsum + reverse gives suffix sums.
    tp_cum = np.cumsum(hist_pos[::-1])[::-1]
    fp_cum = np.cumsum(hist_neg[::-1])[::-1]

    total_pos = int(tp_cum[0])
    total_neg = int(fp_cum[0])

    # ---------------------------
    # HARD ASSERTS (fail fast)
    # ---------------------------
    if total_pos <= 0:
        raise RuntimeError(
            f"[compute_metrics_histogram] Degenerate pool: total_pos={total_pos}. "
            "No positive pixels in optimization pool => TPR/MCC selection is invalid."
        )
    if total_neg <= 0:
        raise RuntimeError(
            f"[compute_metrics_histogram] Degenerate pool: total_neg={total_neg}. "
            "No negative pixels in optimization pool => TNR/MCC selection is invalid."
        )

    fn_cum = total_pos - tp_cum
    tn_cum = total_neg - fp_cum

    # 4) Metric vectors
    EPS = 1e-7
    tpr_vec = tp_cum.astype(np.float64) / (total_pos + EPS)

    tnr_vec = tn_cum.astype(np.float64) / (total_neg + EPS)
    if not np.all(np.isfinite(tnr_vec)):
        bad = np.where(~np.isfinite(tnr_vec))[0][:10]
        raise RuntimeError(
            f"[compute_metrics_histogram] Non-finite values in tnr_vec at bins {bad.tolist()} "
            f"(total_pos={total_pos}, total_neg={total_neg})."
        )

    # MCC denominator in float64 to avoid int64 overflow
    a = (tp_cum + fp_cum).astype(np.float64)
    b = (tp_cum + fn_cum).astype(np.float64)
    c = (tn_cum + fp_cum).astype(np.float64)
    d = (tn_cum + fn_cum).astype(np.float64)

    denom2 = a * b * c * d
    # Guard against tiny negative due to floating-point roundoff (should be rare)
    denom2 = np.maximum(denom2, 0.0)
    denom = np.sqrt(denom2)

    num = (tp_cum.astype(np.float64) * tn_cum.astype(np.float64) -
          fp_cum.astype(np.float64) * fn_cum.astype(np.float64))
    mcc_vec = num / (denom + EPS)

    # Only required when sec_metric == "mcc", but checking here is cheap and safer
    if sec_metric == "mcc":
        if not np.all(np.isfinite(mcc_vec)):
            bad = np.where(~np.isfinite(mcc_vec))[0][:10]
            raise RuntimeError(
                f"[compute_metrics_histogram] Non-finite values in mcc_vec at bins {bad.tolist()} "
                f"(total_pos={total_pos}, total_neg={total_neg})."
            )

    # If you want float32 downstream (optional)
    tpr_vec = tpr_vec.astype(np.float32)
    tnr_vec = tnr_vec.astype(np.float32)
    mcc_vec = mcc_vec.astype(np.float32)

    # Threshold value per bin (consistent with binning rule: bin = floor(p*N_BINS))
    thresholds_vec = np.linspace(0.0, 1.0, N_BINS + 1, dtype=np.float32)

    # 5) Select best threshold subject to TPR constraint
    valid = np.where(tpr_vec >= tpr_target)[0]

    if valid.size:
        if sec_metric == "tnr":
            best_local_idx = valid[np.argmax(tnr_vec[valid])]
            best_score = float(tnr_vec[best_local_idx])
        else:
            best_local_idx = valid[np.argmax(mcc_vec[valid])]
            best_score = float(mcc_vec[best_local_idx])
    else:
        # Fallback: maximize TPR if target unreachable
        best_local_idx = int(np.argmax(tpr_vec))
        best_score = float(tnr_vec[best_local_idx] if sec_metric == "tnr" else mcc_vec[best_local_idx])

    return float(thresholds_vec[best_local_idx]), best_score

def check_patient_collapse_streamed(weights, pred_mms, trues_mm, pat_map, patient_list, thr, tpr_floor):
    tpr_sum = 0
    n_pats = 0
    weights = np.array(weights, dtype=np.float32)
    active_indices = [i for i, w in enumerate(weights) if w > 1e-4]

    for p in patient_list:
        idxs = pat_map[p]
        pat_gt = trues_mm[idxs]
        if np.sum(pat_gt) == 0: continue

        # Compute Ensemble for this patient
        pat_ens = np.zeros(pat_gt.shape, dtype=np.float32)
        for mi in active_indices:
            # Decode uint16 -> float
            w_eff = weights[mi] / 65535.0
            pat_ens += pred_mms[mi][idxs].astype(np.float32) * w_eff

        tp = np.sum((pat_ens >= thr) & (pat_gt == 1))
        fn = np.sum((pat_ens < thr)  & (pat_gt == 1))

        tpr = tp / (tp + fn + 1e-7)
        tpr_sum += tpr
        n_pats += 1

    if n_pats == 0: return 1.0
    return tpr_sum / n_pats

def pick_n(total, frac):
    if total <= 1:
        return 0  # can't hold out without killing opt pool
    # at least 1, but leave at least 1 for opt
    return min(max(1, int(round(total * frac))), total - 1)

# --- REFACTORED OBJECTIVE FUNCTION (STREAMING) ---
def objective_semantic_streaming(trial):
    # 1. Suggest Weights
    ws = [trial.suggest_float(f"w_sem_{i}", 0.0, 1.0) for i in range(len(sem_indices))]
    w_sum = sum(ws) + 1e-9
    ws = [w/w_sum for w in ws] # Normalize

    # 2. Suggest ROI Operating Point
    # FIX: Increased lower bound from 0.05 to 0.15.
    # 0.05 captures background noise, causing "Trivial Permissive" pruning.
    roi_thresh = trial.suggest_float("roi_thresh", 0.15, 0.60)

    # 3. Stream Processing (Patient-wise) to save RAM
    roi_area_fracs = []
    roi_pos_recalls = []
    n_empty_rois = 0

    # Pre-calculate effective weights for uint16->float conversion
    # w_eff[i] = weight[i] / 65535.0
    w_eff_list = [w / 65535.0 for w in ws]

    # Iterate over patients instead of loading full dataset
    for p in opt_pats:
        sl = opt_pat_map_local[p]

        pat_global_indices = opt_idx[sl]

        pat_u16_arrays = [pred_mms[i][pat_global_indices] for i in sem_indices]

        # Weighted sum (Numpy is efficient here for small chunks)
        # pat_ens shape: [Frames, H, W]
        pat_ens = np.zeros(pat_u16_arrays[0].shape, dtype=np.float32)
        for i, u16_arr in enumerate(pat_u16_arrays):
            if w_eff_list[i] > 1e-7:
                pat_ens += u16_arr.astype(np.float32) * w_eff_list[i]

        # B. Generate ROI (Using Torch on CPU for this small chunk)
        # This keeps peak memory low (Batch Size = Patient Size)
        t_probs = torch.from_numpy(pat_ens)
        t_roi = generate_roi_batch(t_probs, ROI_CONTEXT_SCALE, roi_thresh)
        p_roi = t_roi.numpy().astype(np.uint8) # [Frames, H, W]

        # C. Get Ground Truth
        p_gt = opt_gt_u8[sl]

        # D. Metrics
        area_frac = np.mean(p_roi)
        roi_area_fracs.append(area_frac)

        if np.sum(p_roi) == 0:
            n_empty_rois += 1

        is_pos_pat = (np.sum(p_gt) > 0)
        if is_pos_pat:
            # Intersection count
            # Use bitwise & for speed on uint8/bool
            intersection = np.sum((p_roi == 1) & (p_gt == 1))
            total_pos = np.sum(p_gt)
            recall = intersection / (total_pos + 1e-7)
            roi_pos_recalls.append(recall)

        # E. Explicit cleanup (Optional but safe)
        del pat_ens, t_probs, t_roi, p_roi, pat_u16_arrays

    # 4. Aggregates
    median_area = np.median(roi_area_fracs) if roi_area_fracs else 0.0
    empty_rate = n_empty_rois / len(opt_pats)
    mean_pos_recall = np.mean(roi_pos_recalls) if roi_pos_recalls else 0.0

    # 5. Guardrails
    # =========================================================================
    # UPDATED GUARDRAILS (Sensitive to Dense Data)
    # =========================================================================

    # Check 1: Empty ROI (Still bad, keep this)
    if empty_rate > ROI_EMPTY_MAX:
        raise optuna.exceptions.TrialPruned(f"Trivial Empty: {empty_rate:.2f}")

    # Check 2: Misses Positives (Still bad, keep this)
    if mean_pos_recall < ROI_MIN_POS_RECALL:
        raise optuna.exceptions.TrialPruned(f"Misses Positives: {mean_pos_recall:.2f}")

    # Check 3: Trivial Permissive (RELAXED)
    # If the Ground Truth itself is dense (e.g. >50% tumor), we must allow high area.
    # We estimate GT density from the loaded `p_gt` slices.

    # Calculate GT density for the opt set
    gt_densities = []
    for p in opt_pats:
        sl = opt_pat_map_local[p]
        gt_densities.append(np.mean(opt_gt_u8[sl]))
    mean_gt_density = np.mean(gt_densities) if gt_densities else 0.0

    # Dynamic Ceiling: Allow ROI to be slightly larger than GT density
    # If GT is 0.9 (90% tumor), allow ROI up to 0.99
    # If GT is 0.01 (1% tumor), allow ROI up to 0.60
    dynamic_max_median = max(ROI_MAX_MEDIAN, mean_gt_density + 0.15)

    if median_area > dynamic_max_median:
        raise optuna.exceptions.TrialPruned(f"Trivial Permissive: {median_area:.2f} > {dynamic_max_median:.2f}")

    return mean_pos_recall

def objective_spatial_streaming(trial):
    # 1. Suggest Weights
    ws = [trial.suggest_float(f"w_spa_{i}", 0.0, 1.0) for i in range(len(spa_indices))]
    w_sum = sum(ws) + 1e-9
    ws = [w / w_sum for w in ws]

    # Note: We do NOT materialize the full 'p_spa_ens' here anymore.
    # This prevents the ~4GB RAM spike per trial.

    auprc_accum = 0.0
    spill_accum = 0.0
    n_eval_pats = 0

    # 2. Stream Processing (Patient-wise)
    for p in opt_pats:
        sl = opt_pat_map_local[p]   # Slice for this patient

        # A. Get Context (GT and Fixed ROI)
        p_gt  = opt_gt_u8[sl]
        p_roi = fixed_roi_mask[sl]

        # Filter: Positive Only Policy
        is_pos_pat = (np.sum(p_gt) > 0)
        if SPATIAL_PATIENT_POLICY == "positive_only" and not is_pos_pat:
            continue

        pat_global_indices = opt_idx[sl]
        pat_u16_list = [pred_mms[i][pat_global_indices] for i in spa_indices]

        # We use the existing helper function, but only on this small chunk
        # Returns float32 [Frames, H, W] for one patient (~50MB vs 4GB)
        p_pred = _weighted_ensemble_from_u16_cache(pat_u16_list, ws)

        # C. Compute Metrics
        # 1) AUPRC inside ROI
        flat_gt   = p_gt.ravel()
        flat_pred = p_pred.ravel()
        flat_roi  = p_roi.ravel()

        score = compute_patient_auprc_in_roi(flat_gt, flat_pred, flat_roi)
        auprc_accum += score

        # 2) Spill Penalty (Mass outside ROI)
        mass_total  = np.sum(p_pred) + 1e-7
        mass_outside = np.sum(p_pred * (1 - p_roi))
        spill = mass_outside / mass_total
        spill_accum += spill

        n_eval_pats += 1

        # D. Explicit Cleanup
        del p_pred, pat_u16_list

    if n_eval_pats == 0:
        return 0.0

    macro_auprc = auprc_accum / n_eval_pats
    macro_spill = spill_accum / n_eval_pats

    return macro_auprc - (SPILL_PENALTY_LAMBDA * macro_spill)

def build_indices_and_local_map(pats_set, pat_map):
    """
    Builds:
      - idx: concatenated frame indices in a deterministic patient order
      - local_map: patient -> slice into arrays indexed by idx
      - sorted_pats: the deterministic patient list used for both
    This guarantees patient slicing is correct for macro/patient metrics.
    """
    sorted_pats = sorted(list(pats_set))
    idx = []
    local_map = {}
    start_ptr = 0
    for p in sorted_pats:
        frames = pat_map[p]
        idx.extend(frames)
        n = len(frames)
        local_map[p] = slice(start_ptr, start_ptr + n)
        start_ptr += n
    return np.array(idx, dtype=np.int64), local_map, sorted_pats

def _weighted_ensemble_from_u16_cache(u16_list, weights):
    """
    u16_list: list of uint16 arrays, each [N_opt, H, W]
    weights : iterable of floats, same length as u16_list

    returns : float32 array [N_opt, H, W] in [0,1]
    """
    scale = 1.0 / 65535.0
    acc = None

    for w, u16 in zip(weights, u16_list):
        if w <= 1e-4:
            continue
        x = u16.astype(np.float32) * (w * scale)
        acc = x if acc is None else (acc + x)

    if acc is None:
        # fallback: all weights ~0
        acc = np.zeros_like(u16_list[0], dtype=np.float32)

    return acc

# --- INSTANTIATE GPU NORMALIZER GLOBALLY ---
gpu_normalizer = GPUNormalizer(
    mean=[0.485, 0.456, 0.406],
    std=[0.229, 0.224, 0.225],
    device=device
)

METADATA_DIR = change_path(METADATA_DIR)
HDF5_DRIVE_DIR = change_path(HDF5_DRIVE_DIR)
OUTPUT_DIR = change_path(OUTPUT_DIR)

# 1. Setup Data
val_h5_path = setup_local_hdf5(HDF5_DRIVE_DIR, LOCAL_DATA_DIR)

print('Loading and Selecting Top N Models...')
top_models_metadata = load_and_select_models(METADATA_DIR, N_TOP_MODELS, SORT_METRIC)

print("Changing paths...")
top_models_metadata = change_paths(top_models_metadata)

ensemble_models = []

constituent_model_info = []
for meta in top_models_metadata:
    # (Same model loading logic as your script)
    try:
        arch, enc, chkpt_path = meta['architecture'], meta['encoder'], meta['checkpoint_path']
        model = get_model(architecture=arch, encoder=enc, validation=True)

        model = load_checkpoint_strict_without_aux(model, chkpt_path, device)

        model.arch_name = arch

        model.eval()

        # Extract hyperparameters safely (default to empty dict if missing)
        hp = meta.get('hyperparameters', {})

        # Explicitly map the training keys to the ensemble report
        # We only keep what is scientifically relevant for the "Recipe"
        model_info = {
            'architecture': meta.get('architecture'),
            'encoder': meta.get('encoder'),
            'checkpoint_path': meta.get('checkpoint_path'),
            'best_model_epoch': meta.get('best_model_epoch'),

            # Map the correct metric name from training
            'best_val_auprc_pixel_score': meta.get('best_val_auprc_pixel_score'),

            # Map the pixel-level threshold used during training monitoring
            'training_monitoring_threshold': meta.get('validation_monitoring_threshold_pixel_level'),

            # Extract nested hyperparameters relevant for reproducibility
            'Learning_rate': hp.get('Learning_rate'),
            'Batch_Size': hp.get('Batch_Size'),
            'Weight_Decay': hp.get('Weight_Decay'),
            'Optimizer': hp.get('Optimizer'),
            'Seed': hp.get('Seed'),
            'Loss_Function': hp.get('Loss_Function')
        }

        ensemble_models.append(model)
        constituent_model_info.append(model_info)
    except Exception as e:
        print(f"Error loading model {meta.get('checkpoint_path')}: {e}")

if len(ensemble_models) < 2:
    print("Error: Fewer than 2 models loaded. Exiting.")
    exit(1)

if len(ensemble_models)<int(N_TOP_MODELS):
  N_EFFECTIVE_MODELS = len(ensemble_models)
  print(f"Warning: Only {len(ensemble_models)} models loaded. Using them all.")
else:
  N_EFFECTIVE_MODELS = int(N_TOP_MODELS)
  print(f"Using the top {N_EFFECTIVE_MODELS} models.")

# 2. CACHE PREDICTIONS (SEQUENTIAL)
# ==========================================
# Instantiate the HDF5 Dataset
full_val_ds = ProstateCancerDatasetHDF5(val_h5_path, mode='validation')

val_loader = DataLoader(
    full_val_ds,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=WORKERS,
    collate_fn=collate_fn
)

pred_paths, trues_path, pids_path, N_total, H, W, trues_mm = cache_predictions_sequential(
    ensemble_models, val_loader, device, PRED_CACHE_DIR
)

# 3. SPLIT DATA (MEMMAP-FRIENDLY)
# ==========================================
with open(pids_path) as f:
  pids = json.load(f)

print("N_total:", len(pids), "unique_pids:", len(set(pids)))
print("sample pids:", list(sorted(set(pids)))[:5])


pat_map = defaultdict(list)
for i, p in enumerate(pids):
  pat_map[p].append(i)
all_pats = list(pat_map.keys())

# Determine tumor status reading from uint8 memmap
pos_pats = []
for p in all_pats:
    # Check if any pixel is positive for this patient
    is_pos = False
    for i in pat_map[p]:
        if np.any(trues_mm[i]):
            is_pos = True
            break
    if is_pos: pos_pats.append(p)

neg_pats = list(set(all_pats) - set(pos_pats))
rng = np.random.default_rng(VAL_HOLDOUT_SEED)
rng.shuffle(pos_pats); rng.shuffle(neg_pats)

# =============================================================================
# MANUAL SPLIT OVERRIDE (For N=5 Small Data)
# =============================================================================
print(f"DEBUG: Pos Pats: {len(pos_pats)}, Neg Pats: {len(neg_pats)}")

# If we have very few patients, ensure we don't accidentally empty the optimization pool
if len(all_pats) <= 10:
    print("WARNING: Small dataset detected (N<=10). Using deterministic Interleaved split.")

    # Interleave them to ensure mix
    # e.g., [Pos, Neg, Pos, Neg, Pos]
    mixed_pats = []
    max_len = max(len(pos_pats), len(neg_pats))
    for i in range(max_len):
        if i < len(pos_pats): mixed_pats.append(pos_pats[i])
        if i < len(neg_pats): mixed_pats.append(neg_pats[i])

    # Take last 1 as holdout, rest as optimization
    # This guarantees the Opt pool has the most data to learn from
    holdout_pats = set([mixed_pats[-1]])
    opt_pats = set(mixed_pats[:-1])
else:
    # Standard logic for larger datasets
    n_h_pos = pick_n(len(pos_pats), VAL_HOLDOUT_FRAC) if len(pos_pats) else 0
    n_h_neg = pick_n(len(neg_pats), VAL_HOLDOUT_FRAC) if len(neg_pats) else 0
    holdout_pats = set(pos_pats[:n_h_pos] + neg_pats[:n_h_neg])
    opt_pats = set(pos_pats[n_h_pos:] + neg_pats[n_h_neg:])

print(f"Final Split -> Opt: {len(opt_pats)}, Holdout: {len(holdout_pats)}")

if (len(pos_pats) + len(neg_pats)) >= 2 and len(holdout_pats) == 0:
    raise RuntimeError(
        "Holdout split produced 0 patients. "
        "Increase VAL_HOLDOUT_FRAC or use a different split policy for small-N validation."
    )

holdout_idx, hold_pat_map_local, sorted_hold_pats = build_indices_and_local_map(holdout_pats, pat_map)
opt_idx, opt_pat_map_local, sorted_opt_pats = build_indices_and_local_map(opt_pats, pat_map)

assert sum(len(pat_map[p]) for p in sorted_opt_pats) == len(opt_idx)
assert sum(len(pat_map[p]) for p in sorted_hold_pats) == len(holdout_idx)

pred_mms = [np.memmap(p, dtype='uint16', mode='r', shape=(N_total, H, W)) for p in pred_paths]

# =============================================================================
# NEW: Stream Optimization (Replaces Old Stage 1 & 2)
# =============================================================================

# 4. Split Models
sem_indices = []
spa_indices = []
print("\n--- Splitting Models into Streams ---")
for i, model in enumerate(ensemble_models):
    stype = get_stream_type(model.arch_name)
    print(f"Model {i}: {model.arch_name} -> {stype.upper()}")
    if stype == 'semantic':
      sem_indices.append(i)
    else:
      spa_indices.append(i)

if not sem_indices:
  raise ValueError("No semantic models found based on config.")
if not spa_indices:
  spa_indices = sem_indices # Fallback

# 5. Pre-load Optimization Data
print("Building opt caches (uint16)...")
opt_gt_u8 = trues_mm[opt_idx].astype(np.uint8)  # GT is small and used always

# =============================================================================
# 6. SEMANTIC OPTIMIZATION (UPDATED)
# =============================================================================
print(f"\n{'='*20} Optimizing Semantic Stream {'='*20}")

# Clear any lingering memory before starting
gc.collect()
torch.cuda.empty_cache()

study_sem = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=SEED))

# Insert this before "Optimizing Semantic Stream"
print("--- DEBUG: Checking Model Calibration ---")
for i, idx in enumerate(sem_indices):
    # Load first 1000 pixels of the first patient
    sample = pred_mms[idx][0].astype(np.float32) / 65535.0
    mean_val = np.mean(sample)
    min_val = np.min(sample)
    print(f"Model {i} ({ensemble_models[idx].arch_name}): Mean Pred={mean_val:.4f}, Min Pred={min_val:.4f}")

# Using the new streaming objective function
study_sem.optimize(objective_semantic_streaming, n_trials=N_OPTUNA_TRIALS_SEM)

print("Semantic optimization finished.")
print(f"Best params: {study_sem.best_params}")
print(f"Best value: {study_sem.best_value}")

best_sem_weights_raw = [study_sem.best_params.get(f"w_sem_{i}", 0) for i in range(len(sem_indices))]
s = sum(best_sem_weights_raw) + 1e-9
best_sem_weights = [w/s for w in best_sem_weights_raw]
best_roi_thresh = study_sem.best_params["roi_thresh"]

# =============================================================================
# GENERATE FIXED ROI (Chunked & Streamed from Disk)
# =============================================================================
print("Generating Fixed ROI for Spatial Optimization...")

# 1. Determine shape dynamically from indices and disk memmaps
# opt_idx contains the list of all indices belonging to the optimization set
N_opt = len(opt_idx)
# pred_mms is a list of open memmaps [N_total, H, W]
_, H, W = pred_mms[0].shape

# 2. Allocate the result array
# uint8 is safe for RAM (approx 50MB per 1000 images at 224x224)
fixed_roi_mask = np.zeros((N_opt, H, W), dtype=np.uint8)

# 3. Process in chunks
ROI_GEN_CHUNK = 2048  # Adjust if needed

for i in range(0, N_opt, ROI_GEN_CHUNK):
    end = min(i + ROI_GEN_CHUNK, N_opt)

    # A. Define the GLOBAL indices for this chunk
    # These are the indices in the main pred_mms files
    chunk_global_indices = opt_idx[i:end]

    # B. Read directly from disk (main memmaps)
    # We load ONLY the semantic models for ONLY these indices
    chunk_u16_list = [pred_mms[m_idx][chunk_global_indices] for m_idx in sem_indices]

    # C. Compute Ensemble (Weighted Average)
    # This creates a float32 array for just this chunk
    chunk_probs = _weighted_ensemble_from_u16_cache(chunk_u16_list, best_sem_weights)

    # D. Generate ROI (Thresholding)
    t_probs = torch.from_numpy(chunk_probs)
    t_roi = generate_roi_batch(t_probs, ROI_CONTEXT_SCALE, best_roi_thresh)

    # E. Store result
    fixed_roi_mask[i:end] = t_roi.numpy().astype(np.uint8)

    # F. Cleanup
    del chunk_u16_list, chunk_probs, t_probs, t_roi

print(f"Fixed ROI generated. Shape: {fixed_roi_mask.shape}")

# 7. SPATIAL OPTIMIZATION
print(f"\n{'='*20} Optimizing Spatial Stream {'='*20}")
study_spa = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=SEED))
study_spa.optimize(objective_spatial_streaming, n_trials=N_OPTUNA_TRIALS_SPA)

best_spa_weights_raw = [study_spa.best_params.get(f"w_spa_{i}", 0) for i in range(len(spa_indices))]
s = sum(best_spa_weights_raw) + 1e-9
best_spa_weights = [w/s for w in best_spa_weights_raw]

# =============================================================================
# Final Holdout Eval (Iterative Streaming to prevent RAM Explosion)
# =============================================================================
print("\n=== FINAL HOLDOUT EVALUATION (ITERATIVE STREAMED) ===")

# 1. Setup Accumulators
auprc_accum = 0.0
spill_accum = 0.0
n_eval_pats = 0
n_pos_pats = 0
n_neg_pats = 0

# Helper to compute ensemble without loading all models into RAM at once
def compute_ensemble_iterative(memmaps, model_indices, weights, global_indices, shape_h, shape_w):
    # Allocate accumulator (Float32) - ONE copy in RAM
    n_frames = len(global_indices)
    accumulator = np.zeros((n_frames, shape_h, shape_w), dtype=np.float32)

    # Pre-calculate scale factor
    scale = 1.0 / 65535.0

    for m_idx, w in zip(model_indices, weights):
        if w <= 1e-5: continue # Skip zero-weight models

        # 1. Load ONE model's data from disk
        # This is the only moment high RAM is used for raw data
        chunk = memmaps[m_idx][global_indices]

        # 2. Add to accumulator and scale on the fly
        # We use in-place addition to save memory
        accumulator += chunk.astype(np.float32) * (w * scale)

        # 3. CRITICAL: Delete the chunk immediately
        del chunk

    return accumulator

# 2. Stream through Holdout Patients
for p in tqdm(sorted_hold_pats, desc="Eval Holdout"):
    # Force Garbage Collection per patient to clear previous buffers
    gc.collect()

    sl_local = hold_pat_map_local[p]
    pat_global_indices = holdout_idx[sl_local]

    # Check if patient has data (sanity check)
    if len(pat_global_indices) == 0: continue

    # --- A. Semantic Stream (Iterative) ---
    p_sem = compute_ensemble_iterative(
        pred_mms, sem_indices, best_sem_weights, pat_global_indices, H, W
    )

    # Generate ROI
    t_roi = generate_roi_batch(torch.from_numpy(p_sem), ROI_CONTEXT_SCALE, best_roi_thresh)
    p_roi = t_roi.numpy().astype(np.uint8) # [Frames, H, W]

    # Free Semantic Probability immediately
    del p_sem

    # --- B. Spatial Stream (Iterative) ---
    p_spa = compute_ensemble_iterative(
        pred_mms, spa_indices, best_spa_weights, pat_global_indices, H, W
    )

    # --- C. Metrics ---
    # Load GT for this patient only (avoid pre-loading huge array)
    p_gt = trues_mm[pat_global_indices].astype(np.uint8)

    # Patient Stats
    is_pos_pat = (np.sum(p_gt) > 0)
    if is_pos_pat:
        n_pos_pats += 1
    else:
        n_neg_pats += 1

    # Filter based on policy
    if SPATIAL_PATIENT_POLICY == "positive_only" and not is_pos_pat:
        del t_roi, p_roi, p_spa, p_gt
        continue

    # 1. AUPRC inside ROI
    score = compute_patient_auprc_in_roi(p_gt.ravel(), p_spa.ravel(), p_roi.ravel())
    auprc_accum += score

    # 2. Spill Penalty
    # Note: We use p_spa (ungated) to detect spill outside p_roi
    mass_total = float(np.sum(p_spa) + 1e-7)
    mass_outside = float(np.sum(p_spa * (1 - p_roi)))
    spill = mass_outside / mass_total
    spill_accum += spill

    n_eval_pats += 1

    # --- D. Cleanup ---
    del t_roi, p_roi, p_spa, p_gt

# 4. Final Aggregation
macro_auprc = float(auprc_accum / n_eval_pats) if n_eval_pats > 0 else 0.0
macro_spill = float(spill_accum / n_eval_pats) if n_eval_pats > 0 else 0.0
holdout_objective = float(macro_auprc - (SPILL_PENALTY_LAMBDA * macro_spill))

metrics_out = {
    "Macro_AUPRC_in_ROI": macro_auprc,
    "Macro_Spill": macro_spill,
    "Objective_AUPRC_minus_lambdaSpill": holdout_objective,
    "N_eval_patients": int(n_eval_pats),
    "N_pos_patients_total": int(n_pos_pats),
    "N_neg_patients_total": int(n_neg_pats),
    "Spatial_patient_policy": str(SPATIAL_PATIENT_POLICY),
    "Spill_lambda": float(SPILL_PENALTY_LAMBDA),
}

print(json.dumps(metrics_out, indent=2))

# Save
final_sem_weights = np.zeros(len(ensemble_models))
for i, local_i in enumerate(sem_indices):
  final_sem_weights[local_i] = best_sem_weights[i]

final_spa_weights = np.zeros(len(ensemble_models))
for i, local_i in enumerate(spa_indices):
  final_spa_weights[local_i] = best_spa_weights[i]

# 1. Build a DECLARATIVE Model Registry
# This removes all ambiguity about which weight belongs to which model/checkpoint.
model_registry = []
for j, m in enumerate(ensemble_models):
    # Determine which stream this model belongs to based on your optimization
    stream_type = "none"
    weight = 0.0

    if j in sem_indices:
        stream_type = "semantic"
        weight = float(final_sem_weights[j])
    elif j in spa_indices:
        stream_type = "spatial"
        weight = float(final_spa_weights[j])

    # Create a self-contained record for this model
    model_record = {
        "model_id": f"model_{j}",
        "architecture": str(m.arch_name),
        "encoder": constituent_model_info[j]['encoder'],
        "checkpoint_path": constituent_model_info[j]['checkpoint_path'], # Absolute path
        "stream_role": stream_type,     # 'semantic', 'spatial', or 'none'
        "weight": weight,               # The specific weight for this stream
        "original_index_in_optimizer": int(j)
    }
    model_registry.append(model_record)

# 2. Sort registry by stream and weight (optional, for readability)
model_registry.sort(key=lambda x: (x['stream_role'], x['weight']), reverse=True)

timestamp = get_formatted_datetime_string()

# 3. Create the Final Metadata JSON
metadata = {
    "experiment_id": f"two_stream_opt_{timestamp}",
    "datetime": timestamp,
    "ensemble_strategy": "two_stream_spatial_gating", # Explicit strategy name

    "roi_config": {
        "method": "lowpass_upsample_threshold",
        "scale": ROI_CONTEXT_SCALE,
        "threshold": best_roi_thresh
    },

    "spatial_config": {
        "spill_lambda": SPILL_PENALTY_LAMBDA,
        "patient_policy": SPATIAL_PATIENT_POLICY
    },

    # THIS is the critical part for inference
    "model_registry": model_registry,

    "holdout_metrics": metrics_out
}

# 4. Save
output_json_path = os.path.join(OUTPUT_DIR, f"ENSEMBLE_TWO_STREAM_{timestamp}.json")
with open(output_json_path, 'w') as f:
    json.dump(metadata, f, indent=4)

print(f"\nRobust declarative JSON saved to: {output_json_path}")