# -*- coding: utf-8 -*-
"""AIM_UI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjAwYPTmNQ9wggH5QBwxfDzSe_jv7KA8
"""

# Install required packages
!pip install aim

# --- 1. Imports ---
print("Importing libraries...")
from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata
from aim import Run
import subprocess
import aim
import time
import os

# --- Aim Repository Path ---
AIM_REPO_PATH = "/content/drive/MyDrive/aim_repo_prostate"

# --- 12. Aim & Ngrok Setup ---
print("Setting up Aim repository...")
# --- Aim Setup ---
if not os.path.exists(AIM_REPO_PATH):
  print(f"Aim repository not found at {AIM_REPO_PATH}. Initializing...")
  os.makedirs(AIM_REPO_PATH, exist_ok=True)
  try:
    repo = aim.Repo.init(AIM_REPO_PATH);
    print(f"Aim repository initialized at: {repo.path}")
  except Exception as e:
    print(f"An unexpected error occurred during Aim repo setup: {e}")
else:
  print(f"Using existing Aim repository at: {AIM_REPO_PATH}")

## ---- Ngrok Tunnel Setup -----
# print("Setting up ngrok tunnel...")
# try:
#     ngrok_token = userdata.get('NGROK_TOKEN');
#     ngrok.set_auth_token(ngrok_token)
#     aim_cmd = f"aim up --repo {AIM_REPO_PATH} --port 43800";
#     process = subprocess.Popen(aim_cmd, shell=True);
#     time.sleep(15)
#     active_tunnels = ngrok.get_tunnels();
#     aim_tunnel = None
#     for tunnel in active_tunnels:
#           if tunnel.config['addr'] == 'http://localhost:43800':
#             aim_tunnel = tunnel;
#             break
#     if aim_tunnel is None:
#       aim_tunnel = ngrok.connect(addr="43800", proto="http")
#     print(f"Aim UI available at: {aim_tunnel.public_url}")
# except Exception as e:
#   print(f"Error starting Aim UI or ngrok tunnel: {e}");
#   ngrok.kill()

# ---- Ngrok Tunnel Setup -----
print("Setting up tunnel...")
try:
    aim_cmd = f"aim up --repo {AIM_REPO_PATH} --port 43800";
    process = subprocess.Popen(aim_cmd, shell=True);
    time.sleep(15)
except Exception as e:
  print(f"Error starting Aim UI or ngrok tunnel: {e}");

# Download and set up cloudflared
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

!pkill cloudflared
import time
time.sleep(5)

!./cloudflared tunnel --url http://localhost:43800