# -*- coding: utf-8 -*-
"""APP_IA_MEDICA_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhO0-qGpDSo3R3TCZneOlkjKziSpjW3G
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import userdata

!pip install git+https://github.com/qubvel/segmentation_models.pytorch

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # --- START OF FILE app.py ---
# 
# # --- 1. Imports ---
# print("Importing libraries...")
# import streamlit as st
# import torch
# import torch.nn.functional as F
# import os
# import numpy as np
# from PIL import Image, ImageEnhance
# import gc
# import time
# from datetime import datetime
# import random
# import shutil
# import json
# import cv2
# import segmentation_models_pytorch as smp
# import timm
# import albumentations as A # Still needed for ToTensorV2 if used for model input prep
# from albumentations.pytorch import ToTensorV2
# import tempfile
# import warnings
# warnings.filterwarnings("ignore", category=UserWarning)
# warnings.filterwarnings("ignore", category=FutureWarning)
# import torch.nn as nn
# import traceback
# import io
# 
# # --- PyVips and OpenSlide ---
# try:
#     import pyvips
#     print("PyVips imported successfully.")
# except ImportError:
#     st.error("PyVips not found. Please install it (`pip install pyvips`)")
#     st.stop()
# try:
#     import openslide
#     print("OpenSlide imported successfully.")
# except ImportError:
#     st.error("OpenSlide Python library not found. Ensure it was installed.")
#     st.stop()
# 
# # --- 2. Configuration ---
# st.set_page_config(page_title="Prostate Cancer Segmentation", layout="wide")
# print("Configuring environment...")
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# 
# try:
#     METADATA_DIR = "/content/drive/MyDrive/METADATA_CHECKPOINTS"
#     NORMALIZATION_STATS_PATH = "/content/drive/MyDrive/NORMALIZATION_METADATA/normalization_stats.npz"
#     ENSEMBLE_META_PATH = "/content/drive/MyDrive/ENSEMBLE_METADATA/ensemble_top_8_models_18_04_2025_16_43_37_meta.json"
#     UNICAMP_LOGO_PATH = "/content/drive/MyDrive/LOGOS/unicamp_logo.png"
#     FT_UNICAMP_LOGO_PATH = "/content/drive/MyDrive/LOGOS/ft_unicamp_logo.png"
#     CAPES_LOGO_PATH = "/content/drive/MyDrive/LOGOS/CAPES_logo.png"
#     # Check if essential files exist
#     if not os.path.exists(NORMALIZATION_STATS_PATH):
#       raise FileNotFoundError("Normalization stats file not found.")
#     if not os.path.exists(ENSEMBLE_META_PATH):
#       raise FileNotFoundError("Ensemble metadata file not found.")
# except KeyError as e:
#     st.error(f"Missing required Streamlit secret: {e}.")
#     st.stop()
# except FileNotFoundError as e:
#      st.error(f"Configuration Error: {e}")
#      st.stop()
# except Exception as e:
#     st.error(f"Error during configuration: {e}")
#     st.stop()
# 
# # --- Inference Parameters ---
# BATCH_SIZE_INFERENCE = 32 # Adjust based on GPU memory
# WORKERS = 2
# PATCH_SIZE = 224
# 
# MIN_TISSUE_PERCENTAGE = 0.30 # Your 30% threshold
# KERNEL_OPEN_CV = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3,3)) # For tissue check
# KERNEL_CLOSE_CV = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7,7)) # For tissue check
# PATCH_AREA_CV = PATCH_SIZE * PATCH_SIZE # For tissue check
# DECODER_DROPOUT = 0.0
# 
# BACKLOG_DIR_BASE = "/content/drive/MyDrive/BACKLOG" # Base directory for saving patches
# 
# # --- Seeding (Less critical for inference, but good practice) ---
# SEED = 42;
# random.seed(SEED);
# np.random.seed(SEED);
# torch.manual_seed(SEED)
# if torch.cuda.is_available():
#   torch.cuda.manual_seed_all(SEED)
# 
# print("Configuration complete.")
# 
# 
# # --- Initialize Session State AT THE TOP ---
# if 'processing_complete' not in st.session_state: st.session_state.processing_complete = False
# if 'error_message' not in st.session_state: st.session_state.error_message = None
# if 'wsi_thumb_result' not in st.session_state: st.session_state.wsi_thumb_result = None
# if 'overlay_img_result' not in st.session_state: st.session_state.overlay_img_result = None
# if 'current_file_name' not in st.session_state: st.session_state.current_file_name = None
# if 'last_processed_file_name' not in st.session_state: st.session_state.last_processed_file_name = None
# # --- End Session State Init ---
# 
# 
# # --- 3. Model Definitions ---
# class SwinTransformerSegmentation(nn.Module):
#     # Updated default model name, can still be overridden
#     def __init__(self, out_channels=2, encoder_model='swin_large_patch4_window7_224'): # <-- Changed default
#         super().__init__()
#         print(f"Initializing SwinTransformerSegmentation with encoder: {encoder_model}")
#         # Load pre-trained Swin Transformer backbone
#         self.encoder = timm.create_model(
#             encoder_model,
#             pretrained=True,
#             num_classes=0,
#             in_chans=3,
#             features_only=True
#         )
# 
#         # --- Get Encoder Output Channels Dynamically ---
#         encoder_out_channels = self.encoder.feature_info.channels()[-1] # Get last stage channels
#         print(f"Detected encoder final stage output channels: {encoder_out_channels}") # Should be 1024 for base
# 
#         # --- Segmentation Head (Simple Decoder) ---
#         # Input channels of the first Conv2d MUST match encoder_out_channels
#         self.decoder_head = nn.Sequential(
#             # --- MODIFIED: Input channels updated ---
#             nn.Conv2d(encoder_out_channels, 256, kernel_size=3, padding=1, bias=False), # Use determined channels, maybe bias=False
#             nn.BatchNorm2d(256),
#             nn.ReLU(inplace=True),
#             # --- Optional: Add Dropout ---
#             nn.Dropout2d(p=DECODER_DROPOUT), # Example dropout placement
#             # --- End Optional ---
#             nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False),
#             nn.Conv2d(256, 128, kernel_size=3, padding=1, bias=False),
#             nn.BatchNorm2d(128),
#             nn.ReLU(inplace=True),
#             nn.Dropout2d(p=DECODER_DROPOUT), # Example dropout placement
#             nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False),
#             nn.Conv2d(128, 64, kernel_size=3, padding=1, bias=False),
#             nn.BatchNorm2d(64),
#             nn.ReLU(inplace=True),
#             nn.Dropout2d(p=DECODER_DROPOUT), # Example dropout placement
#             nn.Upsample(scale_factor=8, mode='bilinear', align_corners=False),
#             nn.Conv2d(64, out_channels, kernel_size=1) # Final mapping
#         )
# 
#     def forward(self, x):
#         features_list = self.encoder(x)
#         if not features_list: raise ValueError("Encoder returned empty features list")
#         encoder_output = features_list[-1]
# 
#         # --- Permutation Check (Keep this) ---
#         # Check if channels are last: B, H, W, C -> B, C, H, W
#         if encoder_output.shape[1] != self.encoder.feature_info.channels()[-1]:
#             # print(f"Permuting Swin output: {encoder_output.shape} -> B, C, H, W") # Optional debug
#             encoder_output = encoder_output.permute(0, 3, 1, 2)
# 
#         output = self.decoder_head(encoder_output)
#         return output
# 
# def get_model(architecture,encoder):
# 
#   aux_params=None
#   encoder_weights = None
# 
#   if architecture=="SWIN":
#     model = SwinTransformerSegmentation(out_channels=2)
#   elif architecture=="DEEPLABV3PLUS":
#     model = smp.DeepLabV3Plus(
#         encoder_name=encoder,
#         encoder_weights=encoder_weights,
#         in_channels=3,
#         classes=2,
#         activation=None,
#         decoder_attention_type=None,
#         aux_params=aux_params)
# 
#   elif architecture=="INCEPTIONRESNETV2":
#     model = smp.Unet(
#         encoder_name=encoder,
#         encoder_weights=encoder_weights,
#         in_channels=3,
#         classes=2,
#         activation=None,
#         decoder_attention_type=None,
#         aux_params=aux_params)
# 
#   elif architecture=="DPT":
#     model = smp.DPT(
#         encoder_name=encoder,
#         encoder_weights=encoder_weights,
#         in_channels=3,
#         classes=2,
#         activation=None,
#         decoder_attention_type=None,
#         decoder_readout='ignore',
#         aux_params=aux_params)
#   elif architecture=="UNET++":
#     model = smp.UnetPlusPlus(
#         encoder_name=encoder,
#         encoder_weights=encoder_weights,
#         in_channels=3,
#         classes=2,
#         activation=None,
#         decoder_attention_type=None,
#         aux_params=aux_params)
#   elif architecture=="FPN":
#     model = smp.FPN(
#         encoder_name=encoder,
#         encoder_weights=encoder_weights,
#         in_channels=3,
#         classes=2,
#         activation=None,
#         decoder_attention_type=None,
#         aux_params=aux_params)
#   elif architecture=="SEGFORMER":
#     model = smp.Segformer(
#         encoder_name=encoder,
#         encoder_weights=encoder_weights,
#         in_channels=3,
#         classes=2,
#         activation=None,
#         decoder_attention_type=None,
#         aux_params=aux_params)
#   elif architecture=="MANET":
#     model = smp.MAnet(
#         encoder_name=encoder,
#         encoder_weights=encoder_weights,
#         in_channels=3,
#         classes=2,
#         activation=None,
#         decoder_attention_type=None,
#         aux_params=aux_params)
#   else:
#     raise ValueError(f"Unknown architecture: {architecture}")
# 
#   return model
# 
# 
# # --- 4. Utility and Processing Functions ---
# def clear_gpu():
#      if torch.cuda.is_available():
#       gc.collect();
#       torch.cuda.empty_cache()
# 
# @st.cache_resource(show_spinner="Loading models and normalization stats...")
# def load_dependencies_cached(ensemble_meta_path, normalization_stats_path):
#     ensemble_metadata=None;
#     models_list=[];
#     target_mean=None;
#     target_std=None;
#     optimal_threshold=0.5;
#     model_weights=None
#     try:
#       with open(ensemble_meta_path,'r') as f:
#         ensemble_metadata=json.load(f);
#         optimal_threshold=ensemble_metadata.get('ensemble_optimal_threshold',0.5);
#         model_weights_config=ensemble_metadata.get('ensemble_weights');
#         model_weights=model_weights_config if isinstance(model_weights_config,list) else None;
#         print("Loaded ensemble meta.")
#     except Exception as e:
#       st.error(f"Failed meta load: {e}");
#       return None,None,None,None,None,None
#     try:
#       norm_stats_data=np.load(normalization_stats_path);
#       target_mean=norm_stats_data['template_mean'];
#       target_std=norm_stats_data['template_std'];
#       print("Loaded norm stats.")
#     except Exception as e:
#       st.error(f"Failed norm stats load: {e}");
#       return None,None,None,None,None,None
#     constituent_models=ensemble_metadata.get("constituent_models",[]);
#     if not constituent_models:
#       st.error("No models in meta.");
#       return None,None,None,None,None,None
#     print(f"Loading {len(constituent_models)} models...");
#     model_load_status=st.empty()
#     for i,meta in enumerate(constituent_models):
#         arch=meta.get('architecture');
#         enc=meta.get('encoder');
#         chkpt_path=meta.get('checkpoint_path');
#         dropout=0.0
#         model_load_status.info(f"Load {i+1}/{len(constituent_models)}:{arch}({enc})...");
#         if not all([arch,enc,chkpt_path]) or not os.path.exists(chkpt_path):
#           st.warning(f"Skip model {i+1}");
#           continue
#         try:
#           model_instance=get_model(architecture=arch,encoder=enc);
#           chkpt=torch.load(chkpt_path,map_location=device);
#           state_dict=chkpt['model_state_dict'];
#           is_comp=chkpt.get('is_compiled',False);
#           has_orig=hasattr(model_instance,'_orig_mod');
#           keys_pref=list(state_dict.keys())[0].startswith('_orig_mod.');
#         except Exception as e:
#           st.error(f"Failed model init {i+1}:{e}");
#           return None,None,None,None,None,None
#         try:
#             if is_comp and not has_orig and keys_pref:
#               state_dict={k.replace('_orig_mod.',''):v for k,v in state_dict.items()}
#             elif not is_comp and has_orig and not keys_pref:
#               state_dict={'_orig_mod.'+k:v for k,v in state_dict.items()}
#             model_instance.load_state_dict(state_dict,strict=False);
#             model_instance.to(device);
#             model_instance.eval();
#             models_list.append(model_instance)
#         except Exception as e:
#           st.error(f"Failed state_dict load {i+1}:{e}");
#           return None,None,None,None,None,None
#     model_load_status.success(f"Loaded {len(models_list)} models.");
#     time.sleep(1);
#     model_load_status.empty()
#     print("Dependencies loaded.");
#     return ensemble_metadata,models_list,target_mean,target_std,optimal_threshold,model_weights
# 
# 
# # --- Tissue Detection (from your earlier script) ---
# def check_tissue_percentage_robust(patch_np_rgb, required_percentage=MIN_TISSUE_PERCENTAGE): # Use configured min
#     if patch_np_rgb is None or patch_np_rgb.size == 0:
#       return False
#     try:
#         patch_hsv = cv2.cvtColor(patch_np_rgb, cv2.COLOR_RGB2HSV) # Expects RGB input
#         saturation_channel = patch_hsv[:, :, 1]
#         _, tissue_mask = cv2.threshold(saturation_channel, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
#         tissue_mask = cv2.morphologyEx(tissue_mask, cv2.MORPH_OPEN, KERNEL_OPEN_CV)
#         tissue_mask = cv2.morphologyEx(tissue_mask, cv2.MORPH_CLOSE, KERNEL_CLOSE_CV)
#         tissue_pixels = np.count_nonzero(tissue_mask)
#         tissue_ratio = tissue_pixels / PATCH_AREA_CV
#         return tissue_ratio >= required_percentage
#     except Exception as e:
#         print(f"Error in tissue check: {e}");
#         return False
# 
# # --- Reinhard Normalization (from your earlier script) ---
# def normalize_patch_reinhard(patch_rgb_np, target_mean, target_std, smooth=1e-6):
#     try:
#       patch_bgr=cv2.cvtColor(patch_rgb_np,cv2.COLOR_RGB2BGR);
#       src_lab=cv2.cvtColor(patch_bgr,cv2.COLOR_BGR2LAB).astype(np.float32);
#       src_mean,src_std=cv2.meanStdDev(src_lab);
#       src_mean=np.hstack(src_mean);
#       src_std=np.hstack(src_std);
#       src_std=np.maximum(src_std,smooth);
#       norm_lab=((src_lab-src_mean)*(target_std/src_std))+target_mean;
#       norm_lab=np.clip(norm_lab,0,255).astype(np.uint8);
#       norm_bgr=cv2.cvtColor(norm_lab,cv2.COLOR_LAB2BGR);
#       norm_rgb=cv2.cvtColor(norm_bgr,cv2.COLOR_BGR2RGB);
#       return norm_rgb
#     except Exception as e:
#       print(f"Warn Norm Patch:{e}");
#       return None
# 
# 
# # --- WSI Processing Function (HEAVILY REFACTORED) ---
# def process_wsi(_slide_path, _target_mean_norm, _target_std_norm,
#                  _models_list, _ensemble_weights, _optimal_threshold,
#                  progress_hook=None):
#     patch_size = PATCH_SIZE
#     wsi_thumbnail = None
#     output_canvas_pil = None # For colored overlay full-res image
#     full_resolution_binary_mask_pil = None # For pure binary mask full-res image
# 
#     slide_vips = None
#     slide_os = None # For thumbnail
# 
#     try:
#         print(f"Processing WSI: {_slide_path}")
#         slide_vips = pyvips.Image.openslideload(_slide_path, level=0)
#         slide_os = openslide.OpenSlide(_slide_path)
# 
#         width = slide_vips.width
#         height = slide_vips.height
#         print(f"WSI dimensions (Level 0): {width} x {height}")
# 
#         target_sz=(1024,1024);
#         dims0=(width,height);
#         scale=min(target_sz[0]/dims0[0],target_sz[1]/dims0[1],1.0);
#         thumb_w_disp,thumb_h_disp=int(dims0[0]*scale),int(dims0[1]*scale);
#         wsi_thumbnail = slide_os.get_thumbnail((thumb_w_disp,thumb_h_disp));
#         slide_os.close()
# 
#         output_canvas_pil = Image.new('RGB', (width, height), (230, 230, 230))
#         # --- MODIFICATION: Initialize binary mask canvas ---
#         full_resolution_binary_mask_pil = Image.new('L', (width, height), 0) # 'L' mode for grayscale, 0 for black
# 
#         num_cols = (width + patch_size - 1) // patch_size
#         num_rows = (height + patch_size - 1) // patch_size
#         total_patches = num_cols * num_rows
#         print(f"Total potential patches: {total_patches} ({num_cols}x{num_rows})")
# 
#         if progress_hook:
#           progress_hook(0.0, "Starting WSI processing...")
# 
#         to_tensor_transform = A.Compose([A.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225], max_pixel_value=255.0), ToTensorV2()])
# 
#         num_models = len(_models_list)
#         if _ensemble_weights is None or len(_ensemble_weights) != num_models: # Ensure weights match model count
#             st.warning(f"Ensemble weights are None or mismatched (models: {num_models}, weights: {len(_ensemble_weights) if _ensemble_weights else 0}). Using equal weights.")
#             _ensemble_weights = [1.0/num_models] * num_models
#         for model in _models_list:
#           model.eval()
# 
#         processed_patch_count = 0
#         for r in range(num_rows):
#             for c in range(num_cols):
#                 x = c * patch_size
#                 y = r * patch_size
#                 actual_w = min(patch_size, width - x)
#                 actual_h = min(patch_size, height - y)
# 
#                 if actual_w < patch_size // 4 or actual_h < patch_size // 4: # Adjusted to allow smaller useful patches
#                     processed_patch_count += 1
#                     continue
# 
#                 try:
#                     region_vips = slide_vips.crop(x, y, actual_w, actual_h)
#                     patch_np_rgb = np.ndarray(
#                         buffer=region_vips.write_to_memory(),
#                         dtype=np.uint8,
#                         shape=[region_vips.height, region_vips.width, region_vips.bands]
#                     )
#                     if patch_np_rgb.shape[2] == 4: patch_np_rgb = patch_np_rgb[:, :, :3]
# 
#                     # Pad if patch is smaller than standard patch_size for consistent processing
#                     current_patch_for_processing = patch_np_rgb # Store original appearance for pasting if needed
#                     if actual_w < patch_size or actual_h < patch_size:
#                         padded_patch_for_model = np.full((patch_size, patch_size, 3), 230, dtype=np.uint8) # Pad with light gray
#                         padded_patch_for_model[:actual_h, :actual_w, :] = patch_np_rgb
#                         patch_for_model_input = padded_patch_for_model # Use this for tissue check & model
#                     else:
#                         patch_for_model_input = patch_np_rgb # Use original if already correct size
# 
#                 except Exception as e_crop:
#                     print(f"Error cropping patch at ({x},{y}): {e_crop}");
#                     processed_patch_count += 1;
#                     continue
# 
#                 # Use patch_for_model_input (potentially padded) for tissue check
#                 is_tissue = check_tissue_percentage_robust(patch_for_model_input, required_percentage=MIN_TISSUE_PERCENTAGE)
# 
#                 # Initialize pred_mask_binary for this patch (all zeros if not processed/no tissue)
#                 # This ensures it's defined for pasting onto full_resolution_binary_mask_pil
#                 pred_mask_binary_for_patch = np.zeros((patch_size, patch_size), dtype=np.uint8)
# 
#                 if is_tissue:
#                     patch_norm_rgb = normalize_patch_reinhard(patch_for_model_input, _target_mean_norm, _target_std_norm)
#                     if patch_norm_rgb is None:
#                          output_canvas_pil.paste(Image.fromarray(current_patch_for_processing), (x,y)); # Paste original appearance
#                          # Binary mask remains all zeros for this patch
#                     else:
#                         img_tensor = to_tensor_transform(image=patch_norm_rgb)["image"].unsqueeze(0).to(device)
#                         sum_probs = torch.zeros((1, patch_size, patch_size), device=device, dtype=torch.float32)
#                         valid_out = 0
#                         try:
#                             with torch.no_grad(), torch.amp.autocast('cuda' if device.type == 'cuda' else 'cpu', enabled=torch.cuda.is_available()):
#                                 for i_m, model in enumerate(_models_list):
#                                     out_raw = model(img_tensor)
#                                     out = out_raw[0] if isinstance(out_raw, tuple) else out_raw
#                                     if not isinstance(out, torch.Tensor):
#                                       continue
#                                     if out.shape[1]==1: probs=torch.sigmoid(out).squeeze(1)
#                                     elif out.shape[1]==2: probs=torch.softmax(out,dim=1)[:,1,:,:]
#                                     else:
#                                       continue
#                                     sum_probs += _ensemble_weights[i_m] * probs;
#                                     valid_out+=1
#                         except Exception as e_infer:
#                             print(f"Infer err patch ({x},{y}):{e_infer}");
#                             output_canvas_pil.paste(Image.fromarray(current_patch_for_processing), (x,y)); # Paste original appearance
#                             # Binary mask remains all zeros
# 
#                         if valid_out > 0:
#                             ens_probs = sum_probs
#                             pred_mask_binary_for_patch = (ens_probs.squeeze(0).cpu().numpy() > _optimal_threshold).astype(np.uint8) # H, W (patch_size x patch_size)
#                             if np.any(pred_mask_binary_for_patch):
#                                 # Create colored overlay for output_canvas_pil
#                                 # Use patch_for_model_input for overlay as it's guaranteed to be patch_size x patch_size
#                                 temp_patch_rgb_for_overlay = patch_for_model_input.copy() # Ensure it's RGB
#                                 colored_mask = np.zeros_like(temp_patch_rgb_for_overlay, dtype=np.uint8)
#                                 colored_mask[pred_mask_binary_for_patch == 1] = [255, 0, 0] # Red for cancer
#                                 alpha = 0.75
#                                 overlaid_patch_np = cv2.addWeighted(temp_patch_rgb_for_overlay, 1, colored_mask, alpha, 0)
# 
#                                 # Crop overlaid_patch_np back to actual_w, actual_h before pasting if padding occurred
#                                 if actual_w < patch_size or actual_h < patch_size:
#                                     output_canvas_pil.paste(Image.fromarray(overlaid_patch_np[:actual_h, :actual_w, :]), (x, y))
#                                 else:
#                                     output_canvas_pil.paste(Image.fromarray(overlaid_patch_np), (x, y))
#                             else: # No cancer, paste original appearance (cropped if necessary)
#                                 output_canvas_pil.paste(Image.fromarray(current_patch_for_processing), (x, y))
#                         else: # No valid model output, paste original appearance (cropped if necessary)
#                             output_canvas_pil.paste(Image.fromarray(current_patch_for_processing), (x, y))
#                 else: # Not enough tissue, just paste the original patch appearance
#                     output_canvas_pil.paste(Image.fromarray(current_patch_for_processing), (x, y))
#                     # Binary mask remains all zeros
# 
#                 # --- MODIFICATION: Paste patch's binary mask onto full binary mask canvas ---
#                 # pred_mask_binary_for_patch is (patch_size, patch_size)
#                 # We need to paste the actual_w, actual_h part of it if padding occurred,
#                 # or ensure it's correctly placed. PIL handles cropping if pasting larger than remaining space.
#                 patch_mask_pil = Image.fromarray((pred_mask_binary_for_patch * 255).astype(np.uint8), mode='L')
# 
#                 # If the patch was padded for the model, only use the mask corresponding to actual region
#                 if actual_w < patch_size or actual_h < patch_size:
#                     patch_mask_pil = patch_mask_pil.crop((0, 0, actual_w, actual_h))
#                 full_resolution_binary_mask_pil.paste(patch_mask_pil, (x, y))
# 
#                 processed_patch_count += 1
#                 if progress_hook and total_patches > 0:
#                     progress_hook(processed_patch_count / total_patches, f"Processing Patches: {processed_patch_count}/{total_patches}")
#                 if processed_patch_count % 100 == 0: clear_gpu()
# 
#         if progress_hook: progress_hook(1.0, "Finalizing image...")
# 
#     except Exception as e:
#         st.error(f"Error during WSI processing: {e}")
#         st.text(traceback.format_exc())
#         # Return what we have, ensure all return values are provided
#         return None, None, wsi_thumbnail # output_canvas_pil, full_resolution_binary_mask_pil, wsi_thumbnail
# 
#     finally:
#         clear_gpu()
#         if slide_vips: del slide_vips
# 
#     print("WSI processing finished.")
#     # --- MODIFICATION: Return all three images ---
#     return output_canvas_pil, full_resolution_binary_mask_pil, wsi_thumbnail
# 
# # Use BLUE color and PIL alpha blending
# # This function is largely fine if mask_pil is a proper L-mode binary mask (0 for no, 255 for yes)
# def create_overlay(thumbnail_pil, mask_pil, color_rgb=(0,0,255), alpha_strength=0.4):
#     if thumbnail_pil is None or mask_pil is None:
#         st.warning("Cannot create overlay: Thumbnail or Mask is None.")
#         return None
#     try:
#         base_image_rgba = thumbnail_pil.convert('RGBA')
#         # Ensure mask_pil is L mode and resized to match thumbnail.
#         # If mask_pil is already the correct size and L mode, this is okay.
#         mask_resized_pil = mask_pil.resize(base_image_rgba.size, Image.NEAREST).convert('L')
# 
#         overlay_color_with_alpha = (*color_rgb, 255)
#         colored_mask_layer = Image.new('RGBA', base_image_rgba.size, overlay_color_with_alpha)
# 
#         mask_np_binary = np.array(mask_resized_pil) # Should be 0 or 255 from a proper binary mask
#         # Alpha calculation: where mask_np_binary is 255 (cancer), alpha is alpha_strength * 255.
#         # Where mask_np_binary is 0 (no cancer), alpha is 0.
#         alpha_values_for_mask = (mask_np_binary.astype(float) * alpha_strength).astype(np.uint8)
#         # Example: if mask_np_binary is 255, (255.0 * 0.4) = 102. Correct.
#         # Example: if mask_np_binary is 0,   (0.0 * 0.4) = 0. Correct.
#         alpha_channel_pil = Image.fromarray(alpha_values_for_mask, mode='L')
# 
#         colored_mask_layer.putalpha(alpha_channel_pil)
#         output_pil = Image.alpha_composite(base_image_rgba, colored_mask_layer)
# 
#         return output_pil.convert('RGB')
# 
#     except Exception as e:
#         st.error(f"Overlay generation error: {e}")
#         st.text(traceback.format_exc())
#         return thumbnail_pil
# 
# # --- MODIFICATION: This function now receives the full binary mask ---
# def create_overlay_display(wsi_thumbnail_pil, full_binary_mask_input_pil, target_display_size=(1024,1024)):
#     """Creates a displayable overlay by resizing the full binary mask to match thumbnail size."""
#     if wsi_thumbnail_pil is None or full_binary_mask_input_pil is None:
#         st.warning("Cannot create display overlay: Thumbnail or Full Binary Mask is None.")
#         return None # Or return wsi_thumbnail_pil as fallback
#     try:
#         # Resize the full_binary_mask_input_pil (which is 'L' mode, 0s and 255s)
#         # to the size of the thumbnail.
#         display_binary_mask_pil = full_binary_mask_input_pil.resize(
#             wsi_thumbnail_pil.size,
#             Image.Resampling.NEAREST # NEAREST is important for masks
#         )
#         # Now, display_binary_mask_pil is an 'L' mode image, correctly sized, with 0s and 255s.
#         return create_overlay(
#             thumbnail_pil=wsi_thumbnail_pil,
#             mask_pil=display_binary_mask_pil, # Pass the correctly prepared binary mask
#             color_rgb=[255,0,0],
#             alpha_strength=0.75 # You can adjust alpha strength here
#         )
# 
#     except Exception as e:
#         st.error(f"Error creating display overlay: {e}")
#         st.text(traceback.format_exc())
#         return wsi_thumbnail_pil # Fallback to original thumbnail
# 
# 
# # --- Streamlit UI ---
# st.markdown("<h1 style='text-align: center; color: #880808;'>Prostate Cancer Ensemble Segmentation</h1>", unsafe_allow_html=True)
# 
# try:
#     ensemble_metadata, models_list, target_mean, target_std, optimal_threshold, model_weights = load_dependencies_cached(ENSEMBLE_META_PATH, NORMALIZATION_STATS_PATH)
#     if ensemble_metadata is None or not models_list or target_mean is None or target_std is None:
#         st.stop()
# except Exception as load_dep_e:
#      st.error(f"Critical error during dependency loading: {load_dep_e}")
#      st.stop()
# 
# # --- Display Sidebar Info ---
# st.sidebar.markdown("## Institutional Support")
# 
# # --- MODIFICATION: USE COLUMNS FOR SIDE-BY-SIDE LOGOS ---
# col1_logo, col2_logo, col3_logo = st.sidebar.columns(3)
# 
# with col1_logo:
#     if UNICAMP_LOGO_PATH.startswith("http"):
#         st.image(UNICAMP_LOGO_PATH, caption="", width=50) # Adjusted width
#     elif os.path.exists(UNICAMP_LOGO_PATH):
#         st.image(UNICAMP_LOGO_PATH, caption="", width=50) # Adjusted width
#     else:
#         st.warning(f"Unicamp logo missing.") # Shorter warning
# 
# with col2_logo:
#     if FT_UNICAMP_LOGO_PATH.startswith("http"):
#         st.image(FT_UNICAMP_LOGO_PATH, caption="", width=50) # Adjusted width
#     elif os.path.exists(FT_UNICAMP_LOGO_PATH):
#         st.image(FT_UNICAMP_LOGO_PATH, caption="", width=50) # Adjusted width
#     else:
#         st.warning(f"FT Unicamp logo missing.") # Shorter warning
# 
# with col3_logo:
#     if CAPES_LOGO_PATH.startswith("http"):
#         st.image(CAPES_LOGO_PATH, caption="", width=50) # Adjust width as needed for CAPES
#     elif os.path.exists(CAPES_LOGO_PATH):
#         st.image(CAPES_LOGO_PATH, caption="", width=50) # Adjust width as needed for CAPES
#     else:
#         st.warning(f"CAPES logo missing.") # Shorter warning
# 
# st.sidebar.markdown("---")
# # --- END OF LOGO MODIFICATION ---
# 
# st.sidebar.header("Active Ensemble Info")
# st.sidebar.metric("Optimal Threshold", f"{optimal_threshold:.4f}")
# st.sidebar.write(f"Number of Models: {len(models_list)}")
# st.sidebar.write(f"Weights: {'Equal' if model_weights is None else [round(w, 3) for w in model_weights]}")
# st.sidebar.write("Constituent Models:")
# for i, m_info in enumerate(ensemble_metadata.get("constituent_models", [])):
#     st.sidebar.text(f" {i+1}. {m_info.get('architecture','?')}")
# 
# uploaded_file = st.file_uploader("Upload WSI file (.svs, .tif)", type=['svs','svslide','tif','tiff'], key="file_uploader")
# 
# col1, col2 = st.columns(2)
# with col1: thumb_container = st.empty()
# with col2: result_container = st.empty()
# button_placeholder = st.empty()
# download_placeholder = st.empty()
# error_placeholder = st.empty()
# 
# 
# if uploaded_file is not None:
#     if uploaded_file.name != st.session_state.last_processed_file_name:
#         st.session_state.results_ready = False
#         st.session_state.wsi_thumb_result = None
#         st.session_state.overlay_img_result = None
#         st.session_state.error_message = None # Changed from processing_error_msg
#         st.session_state.full_res_binary_mask_for_display = None # Reset this too
#         st.session_state.full_res_segmented_image_for_download = None # Reset
#         st.session_state.current_file_name = uploaded_file.name
# 
#     st.write(f"**File:** {uploaded_file.name}")
# 
#     if button_placeholder.button("Run Ensemble Segmentation", key="run_process", use_container_width=True):
#         st.session_state.processing_complete = False
#         st.session_state.error_message = None
#         st.session_state.wsi_thumb_result = None
#         st.session_state.overlay_img_result = None
#         st.session_state.full_res_binary_mask_for_display = None
#         st.session_state.full_res_segmented_image_for_download = None
#         thumb_container.empty(); result_container.empty(); download_placeholder.empty(); error_placeholder.empty();
# 
#         temp_dir = tempfile.mkdtemp(); tmp_slide_path = os.path.join(temp_dir, uploaded_file.name)
#         try:
#             with open(tmp_slide_path, "wb") as f: f.write(uploaded_file.getbuffer())
#             print(f"Saved tmp file: {tmp_slide_path}")
#             if tmp_slide_path and os.path.exists(tmp_slide_path):
#                 start_time = time.time()
#                 main_progress_bar = st.progress(0.0, text="Initializing WSI processing...")
# 
#                 # --- MODIFICATION: process_wsi now returns three items ---
#                 full_res_segmented_colored_image, full_res_binary_mask, wsi_thumbnail_pil = process_wsi(
#                     tmp_slide_path, target_mean, target_std, models_list, model_weights, optimal_threshold,
#                     progress_hook=lambda p, t: main_progress_bar.progress(p, text=t)
#                 )
#                 main_progress_bar.empty()
#                 processing_time = time.time() - start_time
# 
#                 if full_res_binary_mask and wsi_thumbnail_pil: # Check binary mask and thumbnail primarily for display
#                     st.success(f"Processing complete in {processing_time:.2f} seconds.")
# 
#                     # --- MODIFICATION: Use full_res_binary_mask for display overlay ---
#                     display_overlay = create_overlay_display(wsi_thumbnail_pil, full_res_binary_mask)
# 
#                     st.session_state.wsi_thumb_result = wsi_thumbnail_pil
#                     st.session_state.overlay_img_result = display_overlay
#                     st.session_state.full_res_segmented_image_for_download = full_res_segmented_colored_image # Store colored for download
#                     st.session_state.full_res_binary_mask_for_display = full_res_binary_mask # Store binary mask if needed later
#                     st.session_state.results_ready = True
#                     st.session_state.last_processed_file_name = uploaded_file.name
#                 else:
#                   st.session_state.error_message = "Processing failed: Could not generate necessary mask or thumbnail."
#                   if not wsi_thumbnail_pil: st.session_state.error_message += " (Missing WSI thumbnail)"
#                   if not full_res_binary_mask: st.session_state.error_message += " (Missing binary mask)"
# 
#             else:
#               st.session_state.error_message = "Could not save temp file."
#         except Exception as e:
#           st.session_state.error_message = f"Proc Err: {e}\n{traceback.format_exc()}";
#           print(st.session_state.error_message)
#         finally:
#             if 'temp_dir' in locals() and os.path.exists(temp_dir): # Ensure temp_dir is defined
#               try: shutil.rmtree(temp_dir); print("Cleaned temp.")
#               except Exception as e_clean: print(f"Error cleaning temp: {e_clean}")
#             st.rerun()
# 
# 
# if st.session_state.error_message:
#   error_placeholder.error(st.session_state.error_message);
#   button_placeholder.empty(); download_placeholder.empty(); thumb_container.empty(); result_container.empty()
# elif st.session_state.get('results_ready',False) and st.session_state.current_file_name==st.session_state.last_processed_file_name:
#     button_placeholder.empty() # Keep button empty if results are shown
#     if st.session_state.wsi_thumb_result:
#       thumb_container.image(st.session_state.wsi_thumb_result,caption="Original WSI Thumbnail",use_container_width=True)
#     if st.session_state.overlay_img_result:
#          result_container.image(st.session_state.overlay_img_result,caption=f"Segmentation Overlay (Thresh={optimal_threshold:.3f})",use_container_width=True)
#          try:
#             # Save displayed overlay (which is thumbnail sized)
#             overlay_bytes_io = io.BytesIO() # Use io.BytesIO for in-memory file
#             st.session_state.overlay_img_result.save(overlay_bytes_io,format="PNG");
#             overlay_bytes_io.seek(0)
#             download_placeholder.download_button(
#                 label="Download Displayed Overlay (PNG)",
#                 data=overlay_bytes_io,
#                 file_name=f"{os.path.splitext(st.session_state.current_file_name)[0]}_overlay_display.png",
#                 mime="image/png",
#                 key="download_overlay_display" # Unique key
#             )
#             # Optionally, add download for full-resolution colored image
#             if st.session_state.full_res_segmented_image_for_download:
#                 full_res_colored_bytes_io = io.BytesIO()
#                 st.session_state.full_res_segmented_image_for_download.save(full_res_colored_bytes_io, format="PNG") # Or JPEG for smaller size
#                 full_res_colored_bytes_io.seek(0)
#                 download_placeholder.download_button(
#                     label="Download Full-Res Segmented Image (Colored, PNG)",
#                     data=full_res_colored_bytes_io,
#                     file_name=f"{os.path.splitext(st.session_state.current_file_name)[0]}_segmented_full_color.png",
#                     mime="image/png", # or "image/jpeg"
#                     key="download_full_res_color"
#                 )
# 
#          except Exception as e:
#           download_placeholder.error(f"Err download prep: {e}")
#     else:
#       result_container.warning("Overlay not generated.")
# elif uploaded_file is None: # Initial state or after clearing file
#     thumb_container.info("Upload a WSI file to begin.");
#     result_container.info("Results will appear here.")
#     # Button is managed by the uploaded_file check block
# elif st.session_state.current_file_name and not st.session_state.get('results_ready',False): # File uploaded, but not processed yet or new file
#     thumb_container.info("Ready to process. Click 'Run Ensemble Segmentation'.");
#     result_container.info("Segmentation results will appear here after processing.")
# 
# 
# st.markdown("---")
# st.markdown("© App Developed for Research Comparison")
# 
# # --- END OF FILE ---

# --- Cell 1: Installs (Only needs to be run once per session) ---
!apt-get update -qq > /dev/null && apt-get install -y openslide-tools -qq > /dev/null
!pip install -q openslide-python streamlit pandas torch torchvision timm albumentations torchinfo scikit-learn Pillow tqdm opencv-python-headless pyngrok python-dotenv

!apt-get install -y libvips-dev
!pip install pyvips

# --- Cell 2: Create Streamlit Config (Run once per session) ---
!mkdir -p /content/.streamlit
# Write config file

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/.streamlit/config.toml
# [server]
# maxUploadSize = 700
# headless = true
# enableCORS = true
# [client]
# showErrorDetails = true

import time
# Download and set up cloudflared
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

!pkill cloudflared
time.sleep(5)

# Make sure app.py has been created using %%writefile in the previous cell
print("Starting Streamlit app...")
!streamlit run app.py &>/content/streamlit_logs.txt &
time.sleep(10)

!./cloudflared tunnel --url http://localhost:8501